###############################################################################
# Created by write_sdc
###############################################################################
current_design chip_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name core_clock -period 20.0000 [get_ports {clk}]
set_propagated_clock [get_clocks {core_clock}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_addr[0]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_addr[1]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_addr[2]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_addr[3]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[0]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[10]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[11]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[12]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[13]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[14]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[15]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[1]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[2]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[3]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[4]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[5]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[6]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[7]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[8]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_wdata[9]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {cfg_we}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {clear}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[0]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[1]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[2]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[3]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[4]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[5]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[6]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_a[7]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[0]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[1]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[2]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[3]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[4]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[5]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[6]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_b[7]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {inj_valid}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[0]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[1]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[2]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[3]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[4]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[5]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_addr[6]}]
set_input_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {rst}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[0]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[10]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[11]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[12]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[13]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[14]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[15]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[16]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[17]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[18]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[19]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[1]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[20]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[21]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[22]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[23]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[24]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[25]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[26]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[27]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[28]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[29]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[2]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[30]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[31]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[3]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[4]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[5]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[6]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[7]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[8]}]
set_output_delay 4.0000 -clock [get_clocks {core_clock}] -add_delay [get_ports {ro_data[9]}]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
