/* Generated by Yosys 0.69+ (git sha1 20091e4ca, Release, GNU /usr/bin/c++ 11.4.0) [github.com/The-OpenROAD-Project/yosys at master] */

module mac_b1(clk, rst, clear, valid, a, b, acc, out_valid);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input clear;
  wire clear;
  input valid;
  wire valid;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [31:0] acc;
  wire [31:0] acc;
  output out_valid;
  wire out_valid;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire [7:0] \core.a_q ;
  wire [7:0] \core.b_q ;
  wire \core.valid_q ;
  sky130_fd_sc_hd__clkinv_1 _0785_ (
    .A(\core.a_q [7]),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__clkinv_1 _0786_ (
    .A(valid),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__clkinv_1 _0787_ (
    .A(\core.valid_q ),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__clkinv_1 _0788_ (
    .A(acc[1]),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__clkinv_1 _0789_ (
    .A(acc[3]),
    .Y(_0054_)
  );
  sky130_fd_sc_hd__clkinv_1 _0790_ (
    .A(acc[4]),
    .Y(_0055_)
  );
  sky130_fd_sc_hd__clkinv_1 _0791_ (
    .A(acc[5]),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__nand2b_1 _0792_ (
    .A_N(\core.a_q [5]),
    .B(\core.b_q [7]),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__nand2_1 _0793_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [6]),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__nand2_1 _0794_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [5]),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__xnor2_1 _0795_ (
    .A(_0057_),
    .B(_0058_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__maj3_1 _0796_ (
    .A(_0057_),
    .B(_0058_),
    .C(_0059_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__nand2b_1 _0797_ (
    .A_N(\core.a_q [6]),
    .B(\core.b_q [7]),
    .Y(_0062_)
  );
  sky130_fd_sc_hd__o21ai_0 _0798_ (
    .A1(\core.b_q [5]),
    .A2(\core.b_q [6]),
    .B1(\core.a_q [7]),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__a21o_1 _0799_ (
    .A1(\core.b_q [5]),
    .A2(\core.b_q [6]),
    .B1(_0063_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__nor2_1 _0800_ (
    .A(_0062_),
    .B(_0064_),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__xnor2_1 _0801_ (
    .A(_0062_),
    .B(_0064_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__nor2_1 _0802_ (
    .A(_0061_),
    .B(_0066_),
    .Y(_0067_)
  );
  sky130_fd_sc_hd__nand2_1 _0803_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [2]),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__nand2_1 _0804_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [3]),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__and3_1 _0805_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [3]),
    .C(\core.b_q [4]),
    .X(_0070_)
  );
  sky130_fd_sc_hd__o21ai_0 _0806_ (
    .A1(\core.b_q [3]),
    .A2(\core.b_q [4]),
    .B1(\core.a_q [7]),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__nor2_1 _0807_ (
    .A(_0070_),
    .B(_0071_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__xnor2_1 _0808_ (
    .A(_0068_),
    .B(_0072_),
    .Y(_0073_)
  );
  sky130_fd_sc_hd__xor2_1 _0809_ (
    .A(_0068_),
    .B(_0072_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__xor2_1 _0810_ (
    .A(_0061_),
    .B(_0066_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__a21oi_1 _0811_ (
    .A1(_0073_),
    .A2(_0075_),
    .B1(_0067_),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__a21boi_0 _0812_ (
    .A1(_0050_),
    .A2(\core.b_q [7]),
    .B1_N(_0063_),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__and2_0 _0813_ (
    .A(_0074_),
    .B(_0077_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__clkinv_1 _0814_ (
    .A(_0078_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__o21ai_0 _0815_ (
    .A1(_0065_),
    .A2(_0077_),
    .B1(_0074_),
    .Y(_0080_)
  );
  sky130_fd_sc_hd__or3_1 _0816_ (
    .A(_0065_),
    .B(_0074_),
    .C(_0077_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__nand2_1 _0817_ (
    .A(_0080_),
    .B(_0081_),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0818_ (
    .A(_0076_),
    .SLEEP(_0082_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__and2_0 _0819_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [0]),
    .X(_0084_)
  );
  sky130_fd_sc_hd__and3_1 _0820_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [0]),
    .C(\core.b_q [1]),
    .X(_0085_)
  );
  sky130_fd_sc_hd__o21ai_0 _0821_ (
    .A1(\core.b_q [0]),
    .A2(\core.b_q [1]),
    .B1(\core.a_q [7]),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__a21oi_1 _0822_ (
    .A1(\core.b_q [0]),
    .A2(\core.b_q [1]),
    .B1(_0086_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__a21oi_1 _0823_ (
    .A1(acc[13]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0088_)
  );
  sky130_fd_sc_hd__a31oi_1 _0824_ (
    .A1(\core.a_q [7]),
    .A2(\core.b_q [2]),
    .A3(_0072_),
    .B1(_0070_),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__xnor2_1 _0825_ (
    .A(acc[14]),
    .B(_0087_),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__xor2_1 _0826_ (
    .A(_0089_),
    .B(_0090_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__xnor2_1 _0827_ (
    .A(_0088_),
    .B(_0091_),
    .Y(_0092_)
  );
  sky130_fd_sc_hd__xor2_1 _0828_ (
    .A(_0076_),
    .B(_0082_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__nand2_1 _0829_ (
    .A(_0092_),
    .B(_0093_),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__a21oi_1 _0830_ (
    .A1(acc[14]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__xnor2_1 _0831_ (
    .A(acc[15]),
    .B(_0087_),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__xor2_1 _0832_ (
    .A(_0089_),
    .B(_0096_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__xnor2_1 _0833_ (
    .A(_0095_),
    .B(_0097_),
    .Y(_0098_)
  );
  sky130_fd_sc_hd__xnor2_1 _0834_ (
    .A(_0080_),
    .B(_0098_),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__a21oi_1 _0835_ (
    .A1(_0083_),
    .A2(_0094_),
    .B1(_0099_),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__maj3_1 _0836_ (
    .A(_0088_),
    .B(_0089_),
    .C(_0090_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__nand3_1 _0837_ (
    .A(_0083_),
    .B(_0094_),
    .C(_0099_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__nand2b_1 _0838_ (
    .A_N(_0100_),
    .B(_0102_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__nor2_1 _0839_ (
    .A(_0101_),
    .B(_0103_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__maj3_1 _0840_ (
    .A(_0089_),
    .B(_0095_),
    .C(_0096_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__a22oi_1 _0841_ (
    .A1(_0065_),
    .A2(_0074_),
    .B1(_0079_),
    .B2(_0098_),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__a21oi_1 _0842_ (
    .A1(acc[15]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__xnor2_1 _0843_ (
    .A(acc[16]),
    .B(_0087_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__xor2_1 _0844_ (
    .A(_0089_),
    .B(_0108_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__xnor2_1 _0845_ (
    .A(_0107_),
    .B(_0109_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__nor2_1 _0846_ (
    .A(_0078_),
    .B(_0110_),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__xnor2_1 _0847_ (
    .A(_0079_),
    .B(_0110_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__xor2_1 _0848_ (
    .A(_0106_),
    .B(_0112_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__xnor2_1 _0849_ (
    .A(_0105_),
    .B(_0113_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__o21a_1 _0850_ (
    .A1(_0100_),
    .A2(_0104_),
    .B1(_0114_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__maj3_1 _0851_ (
    .A(_0105_),
    .B(_0106_),
    .C(_0112_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__maj3_1 _0852_ (
    .A(_0089_),
    .B(_0107_),
    .C(_0108_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__a21oi_1 _0853_ (
    .A1(acc[16]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__xnor2_1 _0854_ (
    .A(acc[17]),
    .B(_0087_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__xor2_1 _0855_ (
    .A(_0089_),
    .B(_0119_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__xnor2_1 _0856_ (
    .A(_0118_),
    .B(_0120_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__xnor2_1 _0857_ (
    .A(_0111_),
    .B(_0121_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__xnor2_1 _0858_ (
    .A(_0117_),
    .B(_0122_),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__nor2_1 _0859_ (
    .A(_0116_),
    .B(_0123_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__xor2_1 _0860_ (
    .A(_0116_),
    .B(_0123_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__nand2b_1 _0861_ (
    .A_N(\core.a_q [4]),
    .B(\core.b_q [7]),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__nand2_1 _0862_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [6]),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__nand2_1 _0863_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [5]),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__xnor2_1 _0864_ (
    .A(_0126_),
    .B(_0127_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__maj3_1 _0865_ (
    .A(_0126_),
    .B(_0127_),
    .C(_0128_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__xnor2_1 _0866_ (
    .A(_0059_),
    .B(_0060_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__nor2_1 _0867_ (
    .A(_0130_),
    .B(_0131_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__xor2_1 _0868_ (
    .A(_0130_),
    .B(_0131_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__a21oi_1 _0869_ (
    .A1(_0073_),
    .A2(_0133_),
    .B1(_0132_),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__xnor2_1 _0870_ (
    .A(_0074_),
    .B(_0075_),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__nand2b_1 _0871_ (
    .A_N(_0134_),
    .B(_0135_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__a21oi_1 _0872_ (
    .A1(acc[12]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__xnor2_1 _0873_ (
    .A(acc[13]),
    .B(_0087_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__xor2_1 _0874_ (
    .A(_0089_),
    .B(_0138_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__xnor2_1 _0875_ (
    .A(_0137_),
    .B(_0139_),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__xnor2_1 _0876_ (
    .A(_0134_),
    .B(_0135_),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__nand2_1 _0877_ (
    .A(_0140_),
    .B(_0141_),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__xnor2_1 _0878_ (
    .A(_0092_),
    .B(_0093_),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__a21oi_1 _0879_ (
    .A1(_0136_),
    .A2(_0142_),
    .B1(_0143_),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__maj3_1 _0880_ (
    .A(_0089_),
    .B(_0137_),
    .C(_0138_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__nand3_1 _0881_ (
    .A(_0136_),
    .B(_0142_),
    .C(_0143_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__nand2b_1 _0882_ (
    .A_N(_0144_),
    .B(_0146_),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__nor2_1 _0883_ (
    .A(_0145_),
    .B(_0147_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__xor2_1 _0884_ (
    .A(_0101_),
    .B(_0103_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__o21a_1 _0885_ (
    .A1(_0144_),
    .A2(_0148_),
    .B1(_0149_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__nor3_1 _0886_ (
    .A(_0100_),
    .B(_0104_),
    .C(_0114_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__nor2_1 _0887_ (
    .A(_0115_),
    .B(_0151_),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__nand2_1 _0888_ (
    .A(_0150_),
    .B(_0152_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__nand2b_1 _0889_ (
    .A_N(\core.a_q [3]),
    .B(\core.b_q [7]),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__nand2_1 _0890_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [6]),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__nand2_1 _0891_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [5]),
    .Y(_0156_)
  );
  sky130_fd_sc_hd__xnor2_1 _0892_ (
    .A(_0154_),
    .B(_0155_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__maj3_1 _0893_ (
    .A(_0154_),
    .B(_0155_),
    .C(_0156_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__xnor2_1 _0894_ (
    .A(_0128_),
    .B(_0129_),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__nor2_1 _0895_ (
    .A(_0158_),
    .B(_0159_),
    .Y(_0160_)
  );
  sky130_fd_sc_hd__xor2_1 _0896_ (
    .A(_0158_),
    .B(_0159_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__a21oi_1 _0897_ (
    .A1(_0073_),
    .A2(_0161_),
    .B1(_0160_),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__xnor2_1 _0898_ (
    .A(_0074_),
    .B(_0133_),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__nand2b_1 _0899_ (
    .A_N(_0162_),
    .B(_0163_),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__a21oi_1 _0900_ (
    .A1(acc[11]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__xnor2_1 _0901_ (
    .A(acc[12]),
    .B(_0087_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__xor2_1 _0902_ (
    .A(_0089_),
    .B(_0166_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__xnor2_1 _0903_ (
    .A(_0165_),
    .B(_0167_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__xnor2_1 _0904_ (
    .A(_0162_),
    .B(_0163_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__nand2_1 _0905_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__xnor2_1 _0906_ (
    .A(_0140_),
    .B(_0141_),
    .Y(_0171_)
  );
  sky130_fd_sc_hd__a21oi_1 _0907_ (
    .A1(_0164_),
    .A2(_0170_),
    .B1(_0171_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__maj3_1 _0908_ (
    .A(_0089_),
    .B(_0165_),
    .C(_0166_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__nand3_1 _0909_ (
    .A(_0164_),
    .B(_0170_),
    .C(_0171_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nand2b_1 _0910_ (
    .A_N(_0172_),
    .B(_0174_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nor2_1 _0911_ (
    .A(_0173_),
    .B(_0175_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nor2_1 _0912_ (
    .A(_0172_),
    .B(_0176_),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__xnor2_1 _0913_ (
    .A(_0145_),
    .B(_0147_),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__nor2_1 _0914_ (
    .A(_0177_),
    .B(_0178_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__nor3_1 _0915_ (
    .A(_0144_),
    .B(_0148_),
    .C(_0149_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__nor2_1 _0916_ (
    .A(_0150_),
    .B(_0180_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__nor4_1 _0917_ (
    .A(_0150_),
    .B(_0177_),
    .C(_0178_),
    .D(_0180_),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__nand2b_1 _0918_ (
    .A_N(\core.a_q [2]),
    .B(\core.b_q [7]),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__nand2_1 _0919_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [6]),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__nand2_1 _0920_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [5]),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__xnor2_1 _0921_ (
    .A(_0183_),
    .B(_0184_),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__maj3_1 _0922_ (
    .A(_0183_),
    .B(_0184_),
    .C(_0185_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__xnor2_1 _0923_ (
    .A(_0156_),
    .B(_0157_),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__nand2_1 _0924_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [4]),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__nand2_1 _0925_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [3]),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__xor2_1 _0926_ (
    .A(_0069_),
    .B(_0189_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__xnor2_1 _0927_ (
    .A(_0068_),
    .B(_0191_),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__xor2_1 _0928_ (
    .A(_0187_),
    .B(_0188_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__nand2_1 _0929_ (
    .A(_0192_),
    .B(_0193_),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__o21ai_0 _0930_ (
    .A1(_0187_),
    .A2(_0188_),
    .B1(_0194_),
    .Y(_0195_)
  );
  sky130_fd_sc_hd__xnor2_1 _0931_ (
    .A(_0074_),
    .B(_0161_),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__a21oi_1 _0932_ (
    .A1(acc[10]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__maj3_1 _0933_ (
    .A(_0068_),
    .B(_0069_),
    .C(_0189_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__xnor2_1 _0934_ (
    .A(acc[11]),
    .B(_0087_),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__xor2_1 _0935_ (
    .A(_0198_),
    .B(_0199_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__xnor2_1 _0936_ (
    .A(_0197_),
    .B(_0200_),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__xnor2_1 _0937_ (
    .A(_0195_),
    .B(_0196_),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__maj3_1 _0938_ (
    .A(_0195_),
    .B(_0196_),
    .C(_0201_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__xnor2_1 _0939_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0940_ (
    .A(_0203_),
    .SLEEP(_0204_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__maj3_1 _0941_ (
    .A(_0197_),
    .B(_0198_),
    .C(_0199_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__xor2_1 _0942_ (
    .A(_0203_),
    .B(_0204_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__nor2_1 _0943_ (
    .A(_0206_),
    .B(_0207_),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__nor2_1 _0944_ (
    .A(_0205_),
    .B(_0208_),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__xor2_1 _0945_ (
    .A(_0173_),
    .B(_0175_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0946_ (
    .A(_0210_),
    .SLEEP(_0209_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__xnor2_1 _0947_ (
    .A(_0177_),
    .B(_0178_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__clkinv_1 _0948_ (
    .A(_0212_),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__nand2_1 _0949_ (
    .A(_0211_),
    .B(_0213_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__nand2b_1 _0950_ (
    .A_N(\core.a_q [1]),
    .B(\core.b_q [7]),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__nand2_1 _0951_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [6]),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__nand2_1 _0952_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [5]),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__xnor2_1 _0953_ (
    .A(_0215_),
    .B(_0216_),
    .Y(_0218_)
  );
  sky130_fd_sc_hd__maj3_1 _0954_ (
    .A(_0215_),
    .B(_0216_),
    .C(_0217_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__xnor2_1 _0955_ (
    .A(_0185_),
    .B(_0186_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nand2_1 _0956_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [4]),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__nand2_1 _0957_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [3]),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__xnor2_1 _0958_ (
    .A(_0190_),
    .B(_0221_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__xnor2_1 _0959_ (
    .A(_0068_),
    .B(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__maj3_1 _0960_ (
    .A(_0219_),
    .B(_0220_),
    .C(_0224_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__clkinv_1 _0961_ (
    .A(_0225_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__xor2_1 _0962_ (
    .A(_0192_),
    .B(_0193_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__a21oi_1 _0963_ (
    .A1(acc[9]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__maj3_1 _0964_ (
    .A(_0068_),
    .B(_0190_),
    .C(_0221_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__xnor2_1 _0965_ (
    .A(acc[10]),
    .B(_0087_),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__xor2_1 _0966_ (
    .A(_0229_),
    .B(_0230_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__xnor2_1 _0967_ (
    .A(_0228_),
    .B(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__xnor2_1 _0968_ (
    .A(_0226_),
    .B(_0227_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__maj3_1 _0969_ (
    .A(_0226_),
    .B(_0227_),
    .C(_0232_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__xnor2_1 _0970_ (
    .A(_0201_),
    .B(_0202_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__and2_0 _0971_ (
    .A(_0234_),
    .B(_0235_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__maj3_1 _0972_ (
    .A(_0228_),
    .B(_0229_),
    .C(_0230_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__xor2_1 _0973_ (
    .A(_0234_),
    .B(_0235_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0974_ (
    .A(_0238_),
    .SLEEP(_0237_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__xor2_1 _0975_ (
    .A(_0206_),
    .B(_0207_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__o21ai_0 _0976_ (
    .A1(_0236_),
    .A2(_0239_),
    .B1(_0240_),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__xor2_1 _0977_ (
    .A(_0209_),
    .B(_0210_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__nor2_1 _0978_ (
    .A(_0241_),
    .B(_0242_),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__nand2b_1 _0979_ (
    .A_N(\core.a_q [0]),
    .B(\core.b_q [7]),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__nand2_1 _0980_ (
    .A(\core.a_q [1]),
    .B(\core.b_q [6]),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__nand2_1 _0981_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [5]),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__xor2_1 _0982_ (
    .A(_0244_),
    .B(_0245_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__maj3_1 _0983_ (
    .A(_0244_),
    .B(_0245_),
    .C(_0246_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__xnor2_1 _0984_ (
    .A(_0217_),
    .B(_0218_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__nand2_1 _0985_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [2]),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__nand2_1 _0986_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [4]),
    .Y(_0251_)
  );
  sky130_fd_sc_hd__nand2_1 _0987_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [3]),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__xnor2_1 _0988_ (
    .A(_0222_),
    .B(_0251_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__xnor2_1 _0989_ (
    .A(_0250_),
    .B(_0253_),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__maj3_1 _0990_ (
    .A(_0248_),
    .B(_0249_),
    .C(_0254_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__xnor3_1 _0991_ (
    .A(_0219_),
    .B(_0220_),
    .C(_0224_),
    .X(_0256_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0992_ (
    .A(_0256_),
    .SLEEP(_0255_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__a21oi_1 _0993_ (
    .A1(acc[8]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__maj3_1 _0994_ (
    .A(_0222_),
    .B(_0250_),
    .C(_0251_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__xnor2_1 _0995_ (
    .A(acc[9]),
    .B(_0087_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__xor2_1 _0996_ (
    .A(_0259_),
    .B(_0260_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__xnor2_1 _0997_ (
    .A(_0258_),
    .B(_0261_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__xnor2_1 _0998_ (
    .A(_0255_),
    .B(_0256_),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__a21oi_1 _0999_ (
    .A1(_0262_),
    .A2(_0263_),
    .B1(_0257_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__xnor2_1 _1000_ (
    .A(_0232_),
    .B(_0233_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__clkinv_1 _1001_ (
    .A(_0265_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__maj3_1 _1002_ (
    .A(_0258_),
    .B(_0259_),
    .C(_0260_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__maj3_1 _1003_ (
    .A(_0264_),
    .B(_0266_),
    .C(_0267_),
    .X(_0268_)
  );
  sky130_fd_sc_hd__xor2_1 _1004_ (
    .A(_0237_),
    .B(_0238_),
    .X(_0269_)
  );
  sky130_fd_sc_hd__nor2_1 _1005_ (
    .A(_0268_),
    .B(_0269_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__or3_1 _1006_ (
    .A(_0236_),
    .B(_0239_),
    .C(_0240_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__nand2_1 _1007_ (
    .A(_0241_),
    .B(_0271_),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__or3_1 _1008_ (
    .A(_0268_),
    .B(_0269_),
    .C(_0272_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__nand2_1 _1009_ (
    .A(\core.a_q [0]),
    .B(\core.b_q [5]),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__nor2_1 _1010_ (
    .A(_0245_),
    .B(_0274_),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__xnor2_1 _1011_ (
    .A(_0246_),
    .B(_0247_),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__nand2_1 _1012_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [2]),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__nand2_1 _1013_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [4]),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__nand2_1 _1014_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [3]),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__xor2_1 _1015_ (
    .A(_0252_),
    .B(_0278_),
    .X(_0280_)
  );
  sky130_fd_sc_hd__xnor2_1 _1016_ (
    .A(_0277_),
    .B(_0280_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__maj3_1 _1017_ (
    .A(_0275_),
    .B(_0276_),
    .C(_0281_),
    .X(_0282_)
  );
  sky130_fd_sc_hd__xnor3_1 _1018_ (
    .A(_0248_),
    .B(_0249_),
    .C(_0254_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__nand2_1 _1019_ (
    .A(_0282_),
    .B(_0283_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__and2_0 _1020_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [1]),
    .X(_0285_)
  );
  sky130_fd_sc_hd__maj3_1 _1021_ (
    .A(\core.b_q [7]),
    .B(_0084_),
    .C(_0285_),
    .X(_0286_)
  );
  sky130_fd_sc_hd__maj3_1 _1022_ (
    .A(_0252_),
    .B(_0277_),
    .C(_0278_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__xnor2_1 _1023_ (
    .A(acc[8]),
    .B(_0087_),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__nor2_1 _1024_ (
    .A(_0287_),
    .B(_0288_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__xor2_1 _1025_ (
    .A(_0287_),
    .B(_0288_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__xnor2_1 _1026_ (
    .A(_0286_),
    .B(_0290_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__xnor2_1 _1027_ (
    .A(_0282_),
    .B(_0283_),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__o21ai_0 _1028_ (
    .A1(_0291_),
    .A2(_0292_),
    .B1(_0284_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__xor2_1 _1029_ (
    .A(_0262_),
    .B(_0263_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__nand2_1 _1030_ (
    .A(_0293_),
    .B(_0294_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__a21oi_1 _1031_ (
    .A1(_0286_),
    .A2(_0290_),
    .B1(_0289_),
    .Y(_0296_)
  );
  sky130_fd_sc_hd__xnor2_1 _1032_ (
    .A(_0293_),
    .B(_0294_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__o21ai_0 _1033_ (
    .A1(_0296_),
    .A2(_0297_),
    .B1(_0295_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__xnor3_1 _1034_ (
    .A(_0264_),
    .B(_0265_),
    .C(_0267_),
    .X(_0299_)
  );
  sky130_fd_sc_hd__nand2b_1 _1035_ (
    .A_N(_0299_),
    .B(_0298_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__xor2_1 _1036_ (
    .A(_0268_),
    .B(_0269_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__nor2b_1 _1037_ (
    .A(_0300_),
    .B_N(_0301_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__nand2_1 _1038_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [2]),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__nand2_1 _1039_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [4]),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__nand2_1 _1040_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [3]),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__xor2_1 _1041_ (
    .A(_0279_),
    .B(_0304_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__xnor2_1 _1042_ (
    .A(_0303_),
    .B(_0306_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__a22oi_1 _1043_ (
    .A1(\core.a_q [1]),
    .A2(\core.b_q [5]),
    .B1(\core.b_q [6]),
    .B2(\core.a_q [0]),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__nor2_1 _1044_ (
    .A(_0275_),
    .B(_0308_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__and2_0 _1045_ (
    .A(_0307_),
    .B(_0309_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__xor3_1 _1046_ (
    .A(_0275_),
    .B(_0276_),
    .C(_0281_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__nand2_1 _1047_ (
    .A(\core.a_q [6]),
    .B(\core.b_q [0]),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__nand2_1 _1048_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [1]),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__nand2_1 _1049_ (
    .A(\core.a_q [5]),
    .B(\core.b_q [0]),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nand2_1 _1050_ (
    .A(_0312_),
    .B(_0313_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__a32o_1 _1051_ (
    .A1(\core.a_q [5]),
    .A2(\core.b_q [0]),
    .A3(_0285_),
    .B1(_0315_),
    .B2(acc[6]),
    .X(_0316_)
  );
  sky130_fd_sc_hd__maj3_1 _1052_ (
    .A(_0279_),
    .B(_0303_),
    .C(_0304_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__xnor3_1 _1053_ (
    .A(\core.b_q [7]),
    .B(_0084_),
    .C(_0285_),
    .X(_0318_)
  );
  sky130_fd_sc_hd__xor2_1 _1054_ (
    .A(_0317_),
    .B(_0318_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__nand2_1 _1055_ (
    .A(_0316_),
    .B(_0319_),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__xor2_1 _1056_ (
    .A(_0316_),
    .B(_0319_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__maj3_1 _1057_ (
    .A(_0310_),
    .B(_0311_),
    .C(_0321_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__xor2_1 _1058_ (
    .A(_0291_),
    .B(_0292_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__o21ai_0 _1059_ (
    .A1(_0317_),
    .A2(_0318_),
    .B1(_0320_),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__xnor3_1 _1060_ (
    .A(_0291_),
    .B(_0292_),
    .C(_0322_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1061_ (
    .A(_0324_),
    .SLEEP(_0325_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__a21oi_1 _1062_ (
    .A1(_0322_),
    .A2(_0323_),
    .B1(_0326_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__xor2_1 _1063_ (
    .A(_0296_),
    .B(_0297_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1064_ (
    .A(_0328_),
    .SLEEP(_0327_),
    .X(_0329_)
  );
  sky130_fd_sc_hd__xor2_1 _1065_ (
    .A(_0298_),
    .B(_0299_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__or3b_1 _1066_ (
    .A(_0330_),
    .B(_0327_),
    .C_N(_0328_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__xor2_1 _1067_ (
    .A(_0329_),
    .B(_0330_),
    .X(_0332_)
  );
  sky130_fd_sc_hd__nand2_1 _1068_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [2]),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__nand2_1 _1069_ (
    .A(\core.a_q [1]),
    .B(\core.b_q [4]),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__nand2_1 _1070_ (
    .A(\core.a_q [1]),
    .B(\core.b_q [3]),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__xor2_1 _1071_ (
    .A(_0305_),
    .B(_0334_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__xnor2_1 _1072_ (
    .A(_0333_),
    .B(_0336_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__nand3_1 _1073_ (
    .A(\core.a_q [0]),
    .B(\core.b_q [5]),
    .C(_0337_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__xnor2_1 _1074_ (
    .A(_0307_),
    .B(_0309_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__nand2_1 _1075_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [1]),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__nand2_1 _1076_ (
    .A(\core.a_q [4]),
    .B(\core.b_q [0]),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__and2_0 _1077_ (
    .A(_0314_),
    .B(_0340_),
    .X(_0342_)
  );
  sky130_fd_sc_hd__o22ai_1 _1078_ (
    .A1(_0313_),
    .A2(_0341_),
    .B1(_0342_),
    .B2(_0056_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__maj3_1 _1079_ (
    .A(_0305_),
    .B(_0333_),
    .C(_0334_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__xnor3_1 _1080_ (
    .A(acc[6]),
    .B(_0312_),
    .C(_0313_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__xor2_1 _1081_ (
    .A(_0344_),
    .B(_0345_),
    .X(_0346_)
  );
  sky130_fd_sc_hd__nand2_1 _1082_ (
    .A(_0343_),
    .B(_0346_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__xnor2_1 _1083_ (
    .A(_0343_),
    .B(_0346_),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__maj3_1 _1084_ (
    .A(_0338_),
    .B(_0339_),
    .C(_0348_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__xnor3_1 _1085_ (
    .A(_0310_),
    .B(_0311_),
    .C(_0321_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__o21a_1 _1086_ (
    .A1(_0344_),
    .A2(_0345_),
    .B1(_0347_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__xnor2_1 _1087_ (
    .A(_0349_),
    .B(_0350_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__maj3_1 _1088_ (
    .A(_0349_),
    .B(_0350_),
    .C(_0351_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__xnor2_1 _1089_ (
    .A(_0324_),
    .B(_0325_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1090_ (
    .A(_0354_),
    .SLEEP(_0353_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__xnor2_1 _1091_ (
    .A(_0327_),
    .B(_0328_),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__and2_0 _1092_ (
    .A(_0355_),
    .B(_0356_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__nor2_1 _1093_ (
    .A(_0355_),
    .B(_0356_),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nand2_1 _1094_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [1]),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__nand2_1 _1095_ (
    .A(\core.a_q [3]),
    .B(\core.b_q [0]),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__and2_0 _1096_ (
    .A(_0341_),
    .B(_0359_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__o22ai_1 _1097_ (
    .A1(_0340_),
    .A2(_0360_),
    .B1(_0361_),
    .B2(_0055_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__nand2_1 _1098_ (
    .A(\core.a_q [0]),
    .B(\core.b_q [4]),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__nand2_1 _1099_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [2]),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__xor2_1 _1100_ (
    .A(_0335_),
    .B(_0363_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__maj3_1 _1101_ (
    .A(_0335_),
    .B(_0363_),
    .C(_0364_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__xnor3_1 _1102_ (
    .A(acc[5]),
    .B(_0314_),
    .C(_0340_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__nor2_1 _1103_ (
    .A(_0366_),
    .B(_0367_),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__xor2_1 _1104_ (
    .A(_0366_),
    .B(_0367_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__xnor2_1 _1105_ (
    .A(_0362_),
    .B(_0369_),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__xnor2_1 _1106_ (
    .A(_0274_),
    .B(_0337_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__nand2b_1 _1107_ (
    .A_N(_0370_),
    .B(_0371_),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__xnor3_1 _1108_ (
    .A(_0338_),
    .B(_0339_),
    .C(_0348_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__clkinv_1 _1109_ (
    .A(_0373_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__a21oi_1 _1110_ (
    .A1(_0362_),
    .A2(_0369_),
    .B1(_0368_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__maj3_1 _1111_ (
    .A(_0372_),
    .B(_0374_),
    .C(_0375_),
    .X(_0376_)
  );
  sky130_fd_sc_hd__xnor2_1 _1112_ (
    .A(_0351_),
    .B(_0352_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__nor2_1 _1113_ (
    .A(_0376_),
    .B(_0377_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__xor2_1 _1114_ (
    .A(_0376_),
    .B(_0377_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__a21oi_1 _1115_ (
    .A1(acc[7]),
    .A2(_0379_),
    .B1(_0378_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__xnor2_1 _1116_ (
    .A(_0353_),
    .B(_0354_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1117_ (
    .A(_0381_),
    .SLEEP(_0380_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__nand2_1 _1118_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [1]),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__and2_0 _1119_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [0]),
    .X(_0384_)
  );
  sky130_fd_sc_hd__nand2_1 _1120_ (
    .A(\core.a_q [2]),
    .B(\core.b_q [0]),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__and2_0 _1121_ (
    .A(_0360_),
    .B(_0383_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__o22ai_1 _1122_ (
    .A1(_0359_),
    .A2(_0385_),
    .B1(_0386_),
    .B2(_0054_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__nand2_1 _1123_ (
    .A(\core.a_q [0]),
    .B(\core.b_q [2]),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__nand4_1 _1124_ (
    .A(\core.a_q [0]),
    .B(\core.a_q [1]),
    .C(\core.b_q [2]),
    .D(\core.b_q [3]),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__xnor3_1 _1125_ (
    .A(acc[4]),
    .B(_0341_),
    .C(_0359_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__xor2_1 _1126_ (
    .A(_0389_),
    .B(_0390_),
    .X(_0391_)
  );
  sky130_fd_sc_hd__nand2_1 _1127_ (
    .A(_0387_),
    .B(_0391_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1128_ (
    .A(_0387_),
    .SLEEP(_0391_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__xnor2_1 _1129_ (
    .A(_0364_),
    .B(_0365_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__nand3_1 _1130_ (
    .A(_0392_),
    .B(_0393_),
    .C(_0394_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__xor2_1 _1131_ (
    .A(_0370_),
    .B(_0371_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__o21a_1 _1132_ (
    .A1(_0389_),
    .A2(_0390_),
    .B1(_0392_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__maj3_1 _1133_ (
    .A(_0395_),
    .B(_0396_),
    .C(_0397_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__xnor3_1 _1134_ (
    .A(_0372_),
    .B(_0373_),
    .C(_0375_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__nor2_1 _1135_ (
    .A(_0398_),
    .B(_0399_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__xor2_1 _1136_ (
    .A(acc[7]),
    .B(_0379_),
    .X(_0401_)
  );
  sky130_fd_sc_hd__and2_0 _1137_ (
    .A(\core.a_q [1]),
    .B(\core.b_q [1]),
    .X(_0402_)
  );
  sky130_fd_sc_hd__nand2_1 _1138_ (
    .A(\core.a_q [1]),
    .B(\core.b_q [0]),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__xnor2_1 _1139_ (
    .A(_0385_),
    .B(_0402_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__maj3_1 _1140_ (
    .A(acc[2]),
    .B(_0384_),
    .C(_0402_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__xnor3_1 _1141_ (
    .A(acc[3]),
    .B(_0360_),
    .C(_0383_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1142_ (
    .A(_0405_),
    .SLEEP(_0406_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__xnor2_1 _1143_ (
    .A(_0405_),
    .B(_0406_),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__a22oi_1 _1144_ (
    .A1(\core.a_q [1]),
    .A2(\core.b_q [2]),
    .B1(\core.b_q [3]),
    .B2(\core.a_q [0]),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1145_ (
    .A(_0389_),
    .SLEEP(_0409_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__a21oi_1 _1146_ (
    .A1(_0408_),
    .A2(_0410_),
    .B1(_0407_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__xnor3_1 _1147_ (
    .A(_0387_),
    .B(_0391_),
    .C(_0394_),
    .X(_0412_)
  );
  sky130_fd_sc_hd__nor2_1 _1148_ (
    .A(_0411_),
    .B(_0412_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__xnor3_1 _1149_ (
    .A(_0395_),
    .B(_0396_),
    .C(_0397_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__xor2_1 _1150_ (
    .A(_0398_),
    .B(_0399_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__nand3_1 _1151_ (
    .A(_0413_),
    .B(_0414_),
    .C(_0415_),
    .Y(_0416_)
  );
  sky130_fd_sc_hd__nand2_1 _1152_ (
    .A(\core.a_q [0]),
    .B(\core.b_q [1]),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__xor2_1 _1153_ (
    .A(_0403_),
    .B(_0417_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__maj3_1 _1154_ (
    .A(_0053_),
    .B(_0403_),
    .C(_0417_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__xnor2_1 _1155_ (
    .A(acc[2]),
    .B(_0404_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__xor2_1 _1156_ (
    .A(_0419_),
    .B(_0420_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__maj3_1 _1157_ (
    .A(_0388_),
    .B(_0419_),
    .C(_0420_),
    .X(_0422_)
  );
  sky130_fd_sc_hd__xnor2_1 _1158_ (
    .A(_0408_),
    .B(_0410_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__nor2_1 _1159_ (
    .A(_0422_),
    .B(_0423_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__xor2_1 _1160_ (
    .A(_0411_),
    .B(_0412_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__nand3_1 _1161_ (
    .A(\core.a_q [0]),
    .B(\core.b_q [0]),
    .C(acc[0]),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__xnor2_1 _1162_ (
    .A(acc[1]),
    .B(_0418_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__nor2_1 _1163_ (
    .A(_0426_),
    .B(_0427_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__xnor2_1 _1164_ (
    .A(_0388_),
    .B(_0421_),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__xor2_1 _1165_ (
    .A(_0422_),
    .B(_0423_),
    .X(_0430_)
  );
  sky130_fd_sc_hd__nand3_1 _1166_ (
    .A(_0428_),
    .B(_0429_),
    .C(_0430_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__xor2_1 _1167_ (
    .A(_0424_),
    .B(_0425_),
    .X(_0432_)
  );
  sky130_fd_sc_hd__nor2b_1 _1168_ (
    .A(_0431_),
    .B_N(_0432_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__a21oi_1 _1169_ (
    .A1(_0424_),
    .A2(_0425_),
    .B1(_0413_),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__xnor2_1 _1170_ (
    .A(_0414_),
    .B(_0434_),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__a32oi_1 _1171_ (
    .A1(_0414_),
    .A2(_0424_),
    .A3(_0425_),
    .B1(_0433_),
    .B2(_0435_),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__a21oi_1 _1172_ (
    .A1(_0413_),
    .A2(_0414_),
    .B1(_0415_),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1173_ (
    .A(_0416_),
    .SLEEP(_0437_),
    .X(_0438_)
  );
  sky130_fd_sc_hd__o21ai_0 _1174_ (
    .A1(_0436_),
    .A2(_0437_),
    .B1(_0416_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__xor2_1 _1175_ (
    .A(_0400_),
    .B(_0401_),
    .X(_0440_)
  );
  sky130_fd_sc_hd__maj3_1 _1176_ (
    .A(_0400_),
    .B(_0401_),
    .C(_0439_),
    .X(_0441_)
  );
  sky130_fd_sc_hd__xnor2_1 _1177_ (
    .A(_0380_),
    .B(_0381_),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__a21oi_1 _1178_ (
    .A1(_0441_),
    .A2(_0442_),
    .B1(_0382_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__a211oi_1 _1179_ (
    .A1(_0441_),
    .A2(_0442_),
    .B1(_0357_),
    .C1(_0382_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__nor2_1 _1180_ (
    .A(_0358_),
    .B(_0444_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__o31ai_1 _1181_ (
    .A1(_0332_),
    .A2(_0358_),
    .A3(_0444_),
    .B1(_0331_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__xnor2_1 _1182_ (
    .A(_0300_),
    .B(_0301_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__a21oi_1 _1183_ (
    .A1(_0446_),
    .A2(_0447_),
    .B1(_0302_),
    .Y(_0448_)
  );
  sky130_fd_sc_hd__xor2_1 _1184_ (
    .A(_0270_),
    .B(_0272_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__o21ai_0 _1185_ (
    .A1(_0448_),
    .A2(_0449_),
    .B1(_0273_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__xor2_1 _1186_ (
    .A(_0241_),
    .B(_0242_),
    .X(_0451_)
  );
  sky130_fd_sc_hd__a21oi_1 _1187_ (
    .A1(_0450_),
    .A2(_0451_),
    .B1(_0243_),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__xor2_1 _1188_ (
    .A(_0211_),
    .B(_0212_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__o21ai_0 _1189_ (
    .A1(_0452_),
    .A2(_0453_),
    .B1(_0214_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__nor2_1 _1190_ (
    .A(_0179_),
    .B(_0181_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__nor2_1 _1191_ (
    .A(_0182_),
    .B(_0455_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__a21oi_1 _1192_ (
    .A1(_0454_),
    .A2(_0456_),
    .B1(_0182_),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__xnor2_1 _1193_ (
    .A(_0150_),
    .B(_0152_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__o21ai_0 _1194_ (
    .A1(_0457_),
    .A2(_0458_),
    .B1(_0153_),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__xnor2_1 _1195_ (
    .A(_0115_),
    .B(_0125_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__maj3_1 _1196_ (
    .A(_0115_),
    .B(_0125_),
    .C(_0459_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__nor2_1 _1197_ (
    .A(_0078_),
    .B(_0121_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__nand2_1 _1198_ (
    .A(_0110_),
    .B(_0462_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__o21ai_0 _1199_ (
    .A1(_0117_),
    .A2(_0122_),
    .B1(_0463_),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__maj3_1 _1200_ (
    .A(_0089_),
    .B(_0118_),
    .C(_0119_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__a21oi_1 _1201_ (
    .A1(acc[17]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0466_)
  );
  sky130_fd_sc_hd__xnor2_1 _1202_ (
    .A(acc[18]),
    .B(_0087_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__xor2_1 _1203_ (
    .A(_0089_),
    .B(_0467_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__xnor2_1 _1204_ (
    .A(_0466_),
    .B(_0468_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__xnor2_1 _1205_ (
    .A(_0462_),
    .B(_0469_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__nor2_1 _1206_ (
    .A(_0465_),
    .B(_0470_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__xnor2_1 _1207_ (
    .A(_0465_),
    .B(_0470_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__nand2b_1 _1208_ (
    .A_N(_0472_),
    .B(_0464_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__xnor2_1 _1209_ (
    .A(_0464_),
    .B(_0472_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__nand2_1 _1210_ (
    .A(_0124_),
    .B(_0474_),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__xnor2_1 _1211_ (
    .A(_0124_),
    .B(_0474_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__clkinv_1 _1212_ (
    .A(_0476_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__nand2_1 _1213_ (
    .A(_0461_),
    .B(_0477_),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__xnor2_1 _1214_ (
    .A(_0461_),
    .B(_0477_),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__nor2_1 _1215_ (
    .A(rst),
    .B(clear),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1216_ (
    .A(rst),
    .SLEEP(clear),
    .X(_0481_)
  );
  sky130_fd_sc_hd__o21ai_0 _1217_ (
    .A1(\core.valid_q ),
    .A2(acc[18]),
    .B1(_0480_),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__a21oi_1 _1218_ (
    .A1(\core.valid_q ),
    .A2(_0479_),
    .B1(_0482_),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__xnor2_1 _1219_ (
    .A(_0459_),
    .B(_0460_),
    .Y(_0483_)
  );
  sky130_fd_sc_hd__nor2_1 _1220_ (
    .A(_0052_),
    .B(_0483_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__o21ai_0 _1221_ (
    .A1(\core.valid_q ),
    .A2(acc[17]),
    .B1(_0480_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__nor2_1 _1222_ (
    .A(_0484_),
    .B(_0485_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__xnor2_1 _1223_ (
    .A(_0457_),
    .B(_0458_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__o21ai_0 _1224_ (
    .A1(\core.valid_q ),
    .A2(acc[16]),
    .B1(_0480_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__a21oi_1 _1225_ (
    .A1(\core.valid_q ),
    .A2(_0486_),
    .B1(_0487_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__xnor2_1 _1226_ (
    .A(_0454_),
    .B(_0456_),
    .Y(_0488_)
  );
  sky130_fd_sc_hd__o21ai_0 _1227_ (
    .A1(\core.valid_q ),
    .A2(acc[15]),
    .B1(_0480_),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__a21oi_1 _1228_ (
    .A1(\core.valid_q ),
    .A2(_0488_),
    .B1(_0489_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__xnor2_1 _1229_ (
    .A(_0452_),
    .B(_0453_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__o21ai_0 _1230_ (
    .A1(\core.valid_q ),
    .A2(acc[14]),
    .B1(_0480_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__a21oi_1 _1231_ (
    .A1(\core.valid_q ),
    .A2(_0490_),
    .B1(_0491_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__xnor2_1 _1232_ (
    .A(_0450_),
    .B(_0451_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__o21ai_0 _1233_ (
    .A1(\core.valid_q ),
    .A2(acc[13]),
    .B1(_0480_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__a21oi_1 _1234_ (
    .A1(\core.valid_q ),
    .A2(_0492_),
    .B1(_0493_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__xnor2_1 _1235_ (
    .A(_0448_),
    .B(_0449_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__o21ai_0 _1236_ (
    .A1(\core.valid_q ),
    .A2(acc[12]),
    .B1(_0480_),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__a21oi_1 _1237_ (
    .A1(\core.valid_q ),
    .A2(_0494_),
    .B1(_0495_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__xnor2_1 _1238_ (
    .A(_0446_),
    .B(_0447_),
    .Y(_0496_)
  );
  sky130_fd_sc_hd__o21ai_0 _1239_ (
    .A1(\core.valid_q ),
    .A2(acc[11]),
    .B1(_0480_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__a21oi_1 _1240_ (
    .A1(\core.valid_q ),
    .A2(_0496_),
    .B1(_0497_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__xor2_1 _1241_ (
    .A(_0332_),
    .B(_0445_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__o21ai_0 _1242_ (
    .A1(\core.valid_q ),
    .A2(acc[10]),
    .B1(_0480_),
    .Y(_0499_)
  );
  sky130_fd_sc_hd__a21oi_1 _1243_ (
    .A1(\core.valid_q ),
    .A2(_0498_),
    .B1(_0499_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__nor2_1 _1244_ (
    .A(_0052_),
    .B(_0481_),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__o21ai_0 _1245_ (
    .A1(\core.valid_q ),
    .A2(acc[9]),
    .B1(_0480_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1246_ (
    .A(_0357_),
    .SLEEP(_0358_),
    .X(_0501_)
  );
  sky130_fd_sc_hd__xnor2_1 _1247_ (
    .A(_0443_),
    .B(_0501_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__a21oi_1 _1248_ (
    .A1(\core.valid_q ),
    .A2(_0502_),
    .B1(_0500_),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__xnor2_1 _1249_ (
    .A(_0441_),
    .B(_0442_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__o21ai_0 _1250_ (
    .A1(\core.valid_q ),
    .A2(acc[8]),
    .B1(_0480_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__a21oi_1 _1251_ (
    .A1(\core.valid_q ),
    .A2(_0503_),
    .B1(_0504_),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__xnor2_1 _1252_ (
    .A(_0439_),
    .B(_0440_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__o21ai_0 _1253_ (
    .A1(\core.valid_q ),
    .A2(acc[7]),
    .B1(_0480_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__a21oi_1 _1254_ (
    .A1(\core.valid_q ),
    .A2(_0505_),
    .B1(_0506_),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__xor2_1 _1255_ (
    .A(_0436_),
    .B(_0438_),
    .X(_0507_)
  );
  sky130_fd_sc_hd__o21ai_0 _1256_ (
    .A1(\core.valid_q ),
    .A2(acc[6]),
    .B1(_0480_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__a21oi_1 _1257_ (
    .A1(\core.valid_q ),
    .A2(_0507_),
    .B1(_0508_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__xor2_1 _1258_ (
    .A(_0433_),
    .B(_0435_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__nor2_1 _1259_ (
    .A(_0052_),
    .B(_0509_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__a211oi_1 _1260_ (
    .A1(_0052_),
    .A2(_0056_),
    .B1(_0481_),
    .C1(_0510_),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__xor2_1 _1261_ (
    .A(_0431_),
    .B(_0432_),
    .X(_0511_)
  );
  sky130_fd_sc_hd__o21ai_0 _1262_ (
    .A1(\core.valid_q ),
    .A2(acc[4]),
    .B1(_0480_),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__a21oi_1 _1263_ (
    .A1(\core.valid_q ),
    .A2(_0511_),
    .B1(_0512_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__a21o_1 _1264_ (
    .A1(_0428_),
    .A2(_0429_),
    .B1(_0430_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__nand2_1 _1265_ (
    .A(_0431_),
    .B(_0513_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__o21ai_0 _1266_ (
    .A1(\core.valid_q ),
    .A2(acc[3]),
    .B1(_0480_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a21oi_1 _1267_ (
    .A1(\core.valid_q ),
    .A2(_0514_),
    .B1(_0515_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__xnor2_1 _1268_ (
    .A(_0428_),
    .B(_0429_),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__o21ai_0 _1269_ (
    .A1(\core.valid_q ),
    .A2(acc[2]),
    .B1(_0480_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__a21oi_1 _1270_ (
    .A1(\core.valid_q ),
    .A2(_0516_),
    .B1(_0517_),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__xnor2_1 _1271_ (
    .A(_0426_),
    .B(_0427_),
    .Y(_0518_)
  );
  sky130_fd_sc_hd__o21ai_0 _1272_ (
    .A1(\core.valid_q ),
    .A2(acc[1]),
    .B1(_0480_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__a21oi_1 _1273_ (
    .A1(\core.valid_q ),
    .A2(_0518_),
    .B1(_0519_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__and3_1 _1274_ (
    .A(\core.valid_q ),
    .B(\core.a_q [0]),
    .C(\core.b_q [0]),
    .X(_0520_)
  );
  sky130_fd_sc_hd__o21ai_0 _1275_ (
    .A1(acc[0]),
    .A2(_0520_),
    .B1(_0480_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__a21oi_1 _1276_ (
    .A1(acc[0]),
    .A2(_0520_),
    .B1(_0521_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__o21ai_0 _1277_ (
    .A1(_0051_),
    .A2(b[6]),
    .B1(_0480_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__nor2_1 _1278_ (
    .A(valid),
    .B(\core.b_q [6]),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__nor2_1 _1279_ (
    .A(_0522_),
    .B(_0523_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__o21ai_0 _1280_ (
    .A1(_0051_),
    .A2(b[5]),
    .B1(_0480_),
    .Y(_0524_)
  );
  sky130_fd_sc_hd__nor2_1 _1281_ (
    .A(valid),
    .B(\core.b_q [5]),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__nor2_1 _1282_ (
    .A(_0524_),
    .B(_0525_),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__o21ai_0 _1283_ (
    .A1(_0051_),
    .A2(b[4]),
    .B1(_0480_),
    .Y(_0526_)
  );
  sky130_fd_sc_hd__nor2_1 _1284_ (
    .A(valid),
    .B(\core.b_q [4]),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__nor2_1 _1285_ (
    .A(_0526_),
    .B(_0527_),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__o21ai_0 _1286_ (
    .A1(_0051_),
    .A2(b[3]),
    .B1(_0480_),
    .Y(_0528_)
  );
  sky130_fd_sc_hd__nor2_1 _1287_ (
    .A(valid),
    .B(\core.b_q [3]),
    .Y(_0529_)
  );
  sky130_fd_sc_hd__nor2_1 _1288_ (
    .A(_0528_),
    .B(_0529_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__o21ai_0 _1289_ (
    .A1(_0051_),
    .A2(b[2]),
    .B1(_0480_),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__nor2_1 _1290_ (
    .A(valid),
    .B(\core.b_q [2]),
    .Y(_0531_)
  );
  sky130_fd_sc_hd__nor2_1 _1291_ (
    .A(_0530_),
    .B(_0531_),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__o21ai_0 _1292_ (
    .A1(_0051_),
    .A2(b[1]),
    .B1(_0480_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__nor2_1 _1293_ (
    .A(valid),
    .B(\core.b_q [1]),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__nor2_1 _1294_ (
    .A(_0532_),
    .B(_0533_),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__o21ai_0 _1295_ (
    .A1(_0051_),
    .A2(b[0]),
    .B1(_0480_),
    .Y(_0534_)
  );
  sky130_fd_sc_hd__nor2_1 _1296_ (
    .A(valid),
    .B(\core.b_q [0]),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__nor2_1 _1297_ (
    .A(_0534_),
    .B(_0535_),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__o21ai_0 _1298_ (
    .A1(_0051_),
    .A2(a[6]),
    .B1(_0480_),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__nor2_1 _1299_ (
    .A(valid),
    .B(\core.a_q [6]),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__nor2_1 _1300_ (
    .A(_0536_),
    .B(_0537_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__o21ai_0 _1301_ (
    .A1(_0051_),
    .A2(a[5]),
    .B1(_0480_),
    .Y(_0538_)
  );
  sky130_fd_sc_hd__nor2_1 _1302_ (
    .A(valid),
    .B(\core.a_q [5]),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__nor2_1 _1303_ (
    .A(_0538_),
    .B(_0539_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__o21ai_0 _1304_ (
    .A1(_0051_),
    .A2(a[4]),
    .B1(_0480_),
    .Y(_0540_)
  );
  sky130_fd_sc_hd__nor2_1 _1305_ (
    .A(valid),
    .B(\core.a_q [4]),
    .Y(_0541_)
  );
  sky130_fd_sc_hd__nor2_1 _1306_ (
    .A(_0540_),
    .B(_0541_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__o21ai_0 _1307_ (
    .A1(_0051_),
    .A2(a[3]),
    .B1(_0480_),
    .Y(_0542_)
  );
  sky130_fd_sc_hd__nor2_1 _1308_ (
    .A(valid),
    .B(\core.a_q [3]),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__nor2_1 _1309_ (
    .A(_0542_),
    .B(_0543_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__o21ai_0 _1310_ (
    .A1(_0051_),
    .A2(a[2]),
    .B1(_0480_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__nor2_1 _1311_ (
    .A(valid),
    .B(\core.a_q [2]),
    .Y(_0545_)
  );
  sky130_fd_sc_hd__nor2_1 _1312_ (
    .A(_0544_),
    .B(_0545_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__o21ai_0 _1313_ (
    .A1(_0051_),
    .A2(a[1]),
    .B1(_0480_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__nor2_1 _1314_ (
    .A(valid),
    .B(\core.a_q [1]),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__nor2_1 _1315_ (
    .A(_0546_),
    .B(_0547_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__o21ai_0 _1316_ (
    .A1(_0051_),
    .A2(a[0]),
    .B1(_0480_),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__nor2_1 _1317_ (
    .A(valid),
    .B(\core.a_q [0]),
    .Y(_0549_)
  );
  sky130_fd_sc_hd__nor2_1 _1318_ (
    .A(_0548_),
    .B(_0549_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__xnor2_1 _1319_ (
    .A(acc[26]),
    .B(_0087_),
    .Y(_0550_)
  );
  sky130_fd_sc_hd__a21oi_1 _1320_ (
    .A1(acc[25]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__xor2_1 _1321_ (
    .A(_0089_),
    .B(_0550_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__maj3_1 _1322_ (
    .A(_0089_),
    .B(_0550_),
    .C(_0551_),
    .X(_0553_)
  );
  sky130_fd_sc_hd__a21oi_1 _1323_ (
    .A1(acc[26]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0554_)
  );
  sky130_fd_sc_hd__xnor2_1 _1324_ (
    .A(acc[27]),
    .B(_0087_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__xor2_1 _1325_ (
    .A(_0089_),
    .B(_0555_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__xnor2_1 _1326_ (
    .A(_0554_),
    .B(_0556_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__xnor2_1 _1327_ (
    .A(_0551_),
    .B(_0552_),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__nor2_1 _1328_ (
    .A(_0078_),
    .B(_0558_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__xnor2_1 _1329_ (
    .A(_0557_),
    .B(_0559_),
    .Y(_0560_)
  );
  sky130_fd_sc_hd__nor2_1 _1330_ (
    .A(_0078_),
    .B(_0557_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__nand2_1 _1331_ (
    .A(_0558_),
    .B(_0561_),
    .Y(_0562_)
  );
  sky130_fd_sc_hd__o21ai_0 _1332_ (
    .A1(_0553_),
    .A2(_0560_),
    .B1(_0562_),
    .Y(_0563_)
  );
  sky130_fd_sc_hd__maj3_1 _1333_ (
    .A(_0089_),
    .B(_0554_),
    .C(_0555_),
    .X(_0564_)
  );
  sky130_fd_sc_hd__a21oi_1 _1334_ (
    .A1(acc[27]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0565_)
  );
  sky130_fd_sc_hd__xnor2_1 _1335_ (
    .A(acc[28]),
    .B(_0087_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__xor2_1 _1336_ (
    .A(_0089_),
    .B(_0566_),
    .X(_0567_)
  );
  sky130_fd_sc_hd__xnor2_1 _1337_ (
    .A(_0565_),
    .B(_0567_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__xnor2_1 _1338_ (
    .A(_0561_),
    .B(_0568_),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__xnor2_1 _1339_ (
    .A(_0564_),
    .B(_0569_),
    .Y(_0570_)
  );
  sky130_fd_sc_hd__nand2b_1 _1340_ (
    .A_N(_0570_),
    .B(_0563_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__nor2_1 _1341_ (
    .A(_0078_),
    .B(_0568_),
    .Y(_0572_)
  );
  sky130_fd_sc_hd__nand2_1 _1342_ (
    .A(_0557_),
    .B(_0572_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__o21ai_0 _1343_ (
    .A1(_0564_),
    .A2(_0569_),
    .B1(_0573_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__maj3_1 _1344_ (
    .A(_0089_),
    .B(_0565_),
    .C(_0566_),
    .X(_0575_)
  );
  sky130_fd_sc_hd__a21oi_1 _1345_ (
    .A1(acc[28]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__xnor2_1 _1346_ (
    .A(acc[29]),
    .B(_0087_),
    .Y(_0577_)
  );
  sky130_fd_sc_hd__xor2_1 _1347_ (
    .A(_0089_),
    .B(_0577_),
    .X(_0578_)
  );
  sky130_fd_sc_hd__xnor2_1 _1348_ (
    .A(_0576_),
    .B(_0578_),
    .Y(_0579_)
  );
  sky130_fd_sc_hd__xnor2_1 _1349_ (
    .A(_0572_),
    .B(_0579_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__xnor2_1 _1350_ (
    .A(_0575_),
    .B(_0580_),
    .Y(_0581_)
  );
  sky130_fd_sc_hd__nand2b_1 _1351_ (
    .A_N(_0581_),
    .B(_0574_),
    .Y(_0582_)
  );
  sky130_fd_sc_hd__xor2_1 _1352_ (
    .A(_0574_),
    .B(_0581_),
    .X(_0583_)
  );
  sky130_fd_sc_hd__nor2_1 _1353_ (
    .A(_0571_),
    .B(_0583_),
    .Y(_0584_)
  );
  sky130_fd_sc_hd__xnor2_1 _1354_ (
    .A(acc[25]),
    .B(_0087_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__a21oi_1 _1355_ (
    .A1(acc[24]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__xor2_1 _1356_ (
    .A(_0089_),
    .B(_0585_),
    .X(_0587_)
  );
  sky130_fd_sc_hd__maj3_1 _1357_ (
    .A(_0089_),
    .B(_0585_),
    .C(_0586_),
    .X(_0588_)
  );
  sky130_fd_sc_hd__xnor2_1 _1358_ (
    .A(_0586_),
    .B(_0587_),
    .Y(_0589_)
  );
  sky130_fd_sc_hd__nor2_1 _1359_ (
    .A(_0078_),
    .B(_0589_),
    .Y(_0590_)
  );
  sky130_fd_sc_hd__xnor2_1 _1360_ (
    .A(_0558_),
    .B(_0590_),
    .Y(_0591_)
  );
  sky130_fd_sc_hd__nand2_1 _1361_ (
    .A(_0559_),
    .B(_0589_),
    .Y(_0592_)
  );
  sky130_fd_sc_hd__o21ai_0 _1362_ (
    .A1(_0588_),
    .A2(_0591_),
    .B1(_0592_),
    .Y(_0593_)
  );
  sky130_fd_sc_hd__xnor2_1 _1363_ (
    .A(_0553_),
    .B(_0560_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__nand2b_1 _1364_ (
    .A_N(_0594_),
    .B(_0593_),
    .Y(_0595_)
  );
  sky130_fd_sc_hd__xor2_1 _1365_ (
    .A(_0563_),
    .B(_0570_),
    .X(_0596_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1366_ (
    .A(_0595_),
    .SLEEP(_0596_),
    .X(_0597_)
  );
  sky130_fd_sc_hd__xnor2_1 _1367_ (
    .A(acc[24]),
    .B(_0087_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__a21oi_1 _1368_ (
    .A1(acc[23]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0599_)
  );
  sky130_fd_sc_hd__xor2_1 _1369_ (
    .A(_0089_),
    .B(_0598_),
    .X(_0600_)
  );
  sky130_fd_sc_hd__maj3_1 _1370_ (
    .A(_0089_),
    .B(_0598_),
    .C(_0599_),
    .X(_0601_)
  );
  sky130_fd_sc_hd__xnor2_1 _1371_ (
    .A(_0599_),
    .B(_0600_),
    .Y(_0602_)
  );
  sky130_fd_sc_hd__nor2_1 _1372_ (
    .A(_0078_),
    .B(_0602_),
    .Y(_0603_)
  );
  sky130_fd_sc_hd__xnor2_1 _1373_ (
    .A(_0589_),
    .B(_0603_),
    .Y(_0604_)
  );
  sky130_fd_sc_hd__nand2_1 _1374_ (
    .A(_0590_),
    .B(_0602_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__o21ai_0 _1375_ (
    .A1(_0601_),
    .A2(_0604_),
    .B1(_0605_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__xnor2_1 _1376_ (
    .A(_0588_),
    .B(_0591_),
    .Y(_0607_)
  );
  sky130_fd_sc_hd__nand2b_1 _1377_ (
    .A_N(_0607_),
    .B(_0606_),
    .Y(_0608_)
  );
  sky130_fd_sc_hd__xor2_1 _1378_ (
    .A(_0593_),
    .B(_0594_),
    .X(_0609_)
  );
  sky130_fd_sc_hd__nor2_1 _1379_ (
    .A(_0608_),
    .B(_0609_),
    .Y(_0610_)
  );
  sky130_fd_sc_hd__xnor2_1 _1380_ (
    .A(acc[23]),
    .B(_0087_),
    .Y(_0611_)
  );
  sky130_fd_sc_hd__a21oi_1 _1381_ (
    .A1(acc[22]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__xor2_1 _1382_ (
    .A(_0089_),
    .B(_0611_),
    .X(_0613_)
  );
  sky130_fd_sc_hd__maj3_1 _1383_ (
    .A(_0089_),
    .B(_0611_),
    .C(_0612_),
    .X(_0614_)
  );
  sky130_fd_sc_hd__xnor2_1 _1384_ (
    .A(_0612_),
    .B(_0613_),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__nor2_1 _1385_ (
    .A(_0078_),
    .B(_0615_),
    .Y(_0616_)
  );
  sky130_fd_sc_hd__xnor2_1 _1386_ (
    .A(_0602_),
    .B(_0616_),
    .Y(_0617_)
  );
  sky130_fd_sc_hd__nand2_1 _1387_ (
    .A(_0603_),
    .B(_0615_),
    .Y(_0618_)
  );
  sky130_fd_sc_hd__o21ai_0 _1388_ (
    .A1(_0614_),
    .A2(_0617_),
    .B1(_0618_),
    .Y(_0619_)
  );
  sky130_fd_sc_hd__xnor2_1 _1389_ (
    .A(_0601_),
    .B(_0604_),
    .Y(_0620_)
  );
  sky130_fd_sc_hd__nand2b_1 _1390_ (
    .A_N(_0620_),
    .B(_0619_),
    .Y(_0621_)
  );
  sky130_fd_sc_hd__xor2_1 _1391_ (
    .A(_0606_),
    .B(_0607_),
    .X(_0622_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1392_ (
    .A(_0621_),
    .SLEEP(_0622_),
    .X(_0623_)
  );
  sky130_fd_sc_hd__xnor2_1 _1393_ (
    .A(acc[22]),
    .B(_0087_),
    .Y(_0624_)
  );
  sky130_fd_sc_hd__a21oi_1 _1394_ (
    .A1(acc[21]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__xor2_1 _1395_ (
    .A(_0089_),
    .B(_0624_),
    .X(_0626_)
  );
  sky130_fd_sc_hd__maj3_1 _1396_ (
    .A(_0089_),
    .B(_0624_),
    .C(_0625_),
    .X(_0627_)
  );
  sky130_fd_sc_hd__xnor2_1 _1397_ (
    .A(_0625_),
    .B(_0626_),
    .Y(_0628_)
  );
  sky130_fd_sc_hd__nor2_1 _1398_ (
    .A(_0078_),
    .B(_0628_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__xnor2_1 _1399_ (
    .A(_0615_),
    .B(_0629_),
    .Y(_0630_)
  );
  sky130_fd_sc_hd__nand2_1 _1400_ (
    .A(_0616_),
    .B(_0628_),
    .Y(_0631_)
  );
  sky130_fd_sc_hd__o21ai_0 _1401_ (
    .A1(_0627_),
    .A2(_0630_),
    .B1(_0631_),
    .Y(_0632_)
  );
  sky130_fd_sc_hd__xnor2_1 _1402_ (
    .A(_0614_),
    .B(_0617_),
    .Y(_0633_)
  );
  sky130_fd_sc_hd__nand2b_1 _1403_ (
    .A_N(_0633_),
    .B(_0632_),
    .Y(_0634_)
  );
  sky130_fd_sc_hd__xor2_1 _1404_ (
    .A(_0619_),
    .B(_0620_),
    .X(_0635_)
  );
  sky130_fd_sc_hd__nor2_1 _1405_ (
    .A(_0634_),
    .B(_0635_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__xnor2_1 _1406_ (
    .A(acc[21]),
    .B(_0087_),
    .Y(_0637_)
  );
  sky130_fd_sc_hd__a21oi_1 _1407_ (
    .A1(acc[20]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0638_)
  );
  sky130_fd_sc_hd__xor2_1 _1408_ (
    .A(_0089_),
    .B(_0637_),
    .X(_0639_)
  );
  sky130_fd_sc_hd__maj3_1 _1409_ (
    .A(_0089_),
    .B(_0637_),
    .C(_0638_),
    .X(_0640_)
  );
  sky130_fd_sc_hd__xnor2_1 _1410_ (
    .A(_0638_),
    .B(_0639_),
    .Y(_0641_)
  );
  sky130_fd_sc_hd__nor2_1 _1411_ (
    .A(_0078_),
    .B(_0641_),
    .Y(_0642_)
  );
  sky130_fd_sc_hd__xnor2_1 _1412_ (
    .A(_0628_),
    .B(_0642_),
    .Y(_0643_)
  );
  sky130_fd_sc_hd__nand2_1 _1413_ (
    .A(_0629_),
    .B(_0641_),
    .Y(_0644_)
  );
  sky130_fd_sc_hd__o21ai_0 _1414_ (
    .A1(_0640_),
    .A2(_0643_),
    .B1(_0644_),
    .Y(_0645_)
  );
  sky130_fd_sc_hd__xnor2_1 _1415_ (
    .A(_0627_),
    .B(_0630_),
    .Y(_0646_)
  );
  sky130_fd_sc_hd__nand2b_1 _1416_ (
    .A_N(_0646_),
    .B(_0645_),
    .Y(_0647_)
  );
  sky130_fd_sc_hd__xor2_1 _1417_ (
    .A(_0632_),
    .B(_0633_),
    .X(_0648_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1418_ (
    .A(_0647_),
    .SLEEP(_0648_),
    .X(_0649_)
  );
  sky130_fd_sc_hd__xnor2_1 _1419_ (
    .A(acc[20]),
    .B(_0087_),
    .Y(_0650_)
  );
  sky130_fd_sc_hd__a21oi_1 _1420_ (
    .A1(acc[19]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0651_)
  );
  sky130_fd_sc_hd__xor2_1 _1421_ (
    .A(_0089_),
    .B(_0650_),
    .X(_0652_)
  );
  sky130_fd_sc_hd__maj3_1 _1422_ (
    .A(_0089_),
    .B(_0650_),
    .C(_0651_),
    .X(_0653_)
  );
  sky130_fd_sc_hd__xnor2_1 _1423_ (
    .A(_0651_),
    .B(_0652_),
    .Y(_0654_)
  );
  sky130_fd_sc_hd__nor2_1 _1424_ (
    .A(_0078_),
    .B(_0654_),
    .Y(_0655_)
  );
  sky130_fd_sc_hd__xnor2_1 _1425_ (
    .A(_0641_),
    .B(_0655_),
    .Y(_0656_)
  );
  sky130_fd_sc_hd__nand2_1 _1426_ (
    .A(_0642_),
    .B(_0654_),
    .Y(_0657_)
  );
  sky130_fd_sc_hd__o21ai_0 _1427_ (
    .A1(_0653_),
    .A2(_0656_),
    .B1(_0657_),
    .Y(_0658_)
  );
  sky130_fd_sc_hd__xnor2_1 _1428_ (
    .A(_0640_),
    .B(_0643_),
    .Y(_0659_)
  );
  sky130_fd_sc_hd__nand2b_1 _1429_ (
    .A_N(_0659_),
    .B(_0658_),
    .Y(_0660_)
  );
  sky130_fd_sc_hd__xor2_1 _1430_ (
    .A(_0645_),
    .B(_0646_),
    .X(_0661_)
  );
  sky130_fd_sc_hd__nor2_1 _1431_ (
    .A(_0660_),
    .B(_0661_),
    .Y(_0662_)
  );
  sky130_fd_sc_hd__xor2_1 _1432_ (
    .A(_0660_),
    .B(_0661_),
    .X(_0663_)
  );
  sky130_fd_sc_hd__clkinv_1 _1433_ (
    .A(_0663_),
    .Y(_0664_)
  );
  sky130_fd_sc_hd__xnor2_1 _1434_ (
    .A(acc[19]),
    .B(_0087_),
    .Y(_0665_)
  );
  sky130_fd_sc_hd__a21oi_1 _1435_ (
    .A1(acc[18]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0666_)
  );
  sky130_fd_sc_hd__xor2_1 _1436_ (
    .A(_0089_),
    .B(_0665_),
    .X(_0667_)
  );
  sky130_fd_sc_hd__maj3_1 _1437_ (
    .A(_0089_),
    .B(_0665_),
    .C(_0666_),
    .X(_0668_)
  );
  sky130_fd_sc_hd__xnor2_1 _1438_ (
    .A(_0666_),
    .B(_0667_),
    .Y(_0669_)
  );
  sky130_fd_sc_hd__nor2_1 _1439_ (
    .A(_0078_),
    .B(_0669_),
    .Y(_0670_)
  );
  sky130_fd_sc_hd__xnor2_1 _1440_ (
    .A(_0654_),
    .B(_0670_),
    .Y(_0671_)
  );
  sky130_fd_sc_hd__nand2_1 _1441_ (
    .A(_0655_),
    .B(_0669_),
    .Y(_0672_)
  );
  sky130_fd_sc_hd__o21ai_0 _1442_ (
    .A1(_0668_),
    .A2(_0671_),
    .B1(_0672_),
    .Y(_0673_)
  );
  sky130_fd_sc_hd__xnor2_1 _1443_ (
    .A(_0653_),
    .B(_0656_),
    .Y(_0674_)
  );
  sky130_fd_sc_hd__nand2b_1 _1444_ (
    .A_N(_0674_),
    .B(_0673_),
    .Y(_0675_)
  );
  sky130_fd_sc_hd__xor2_1 _1445_ (
    .A(_0658_),
    .B(_0659_),
    .X(_0676_)
  );
  sky130_fd_sc_hd__nor2_1 _1446_ (
    .A(_0675_),
    .B(_0676_),
    .Y(_0677_)
  );
  sky130_fd_sc_hd__maj3_1 _1447_ (
    .A(_0089_),
    .B(_0466_),
    .C(_0467_),
    .X(_0678_)
  );
  sky130_fd_sc_hd__nor2_1 _1448_ (
    .A(_0078_),
    .B(_0469_),
    .Y(_0679_)
  );
  sky130_fd_sc_hd__xnor2_1 _1449_ (
    .A(_0669_),
    .B(_0679_),
    .Y(_0680_)
  );
  sky130_fd_sc_hd__nand2_1 _1450_ (
    .A(_0469_),
    .B(_0670_),
    .Y(_0681_)
  );
  sky130_fd_sc_hd__o21ai_0 _1451_ (
    .A1(_0678_),
    .A2(_0680_),
    .B1(_0681_),
    .Y(_0682_)
  );
  sky130_fd_sc_hd__xnor2_1 _1452_ (
    .A(_0668_),
    .B(_0671_),
    .Y(_0683_)
  );
  sky130_fd_sc_hd__nand2b_1 _1453_ (
    .A_N(_0683_),
    .B(_0682_),
    .Y(_0684_)
  );
  sky130_fd_sc_hd__xor2_1 _1454_ (
    .A(_0673_),
    .B(_0674_),
    .X(_0685_)
  );
  sky130_fd_sc_hd__nor2_1 _1455_ (
    .A(_0684_),
    .B(_0685_),
    .Y(_0686_)
  );
  sky130_fd_sc_hd__xnor2_1 _1456_ (
    .A(_0684_),
    .B(_0685_),
    .Y(_0687_)
  );
  sky130_fd_sc_hd__a21oi_1 _1457_ (
    .A1(_0121_),
    .A2(_0679_),
    .B1(_0471_),
    .Y(_0688_)
  );
  sky130_fd_sc_hd__xnor2_1 _1458_ (
    .A(_0678_),
    .B(_0680_),
    .Y(_0689_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1459_ (
    .A(_0688_),
    .SLEEP(_0689_),
    .X(_0690_)
  );
  sky130_fd_sc_hd__nand2_1 _1460_ (
    .A(_0688_),
    .B(_0689_),
    .Y(_0691_)
  );
  sky130_fd_sc_hd__nand2_1 _1461_ (
    .A(_0690_),
    .B(_0691_),
    .Y(_0692_)
  );
  sky130_fd_sc_hd__xor2_1 _1462_ (
    .A(_0473_),
    .B(_0692_),
    .X(_0693_)
  );
  sky130_fd_sc_hd__a21oi_1 _1463_ (
    .A1(_0473_),
    .A2(_0475_),
    .B1(_0692_),
    .Y(_0694_)
  );
  sky130_fd_sc_hd__a31oi_1 _1464_ (
    .A1(_0461_),
    .A2(_0477_),
    .A3(_0693_),
    .B1(_0694_),
    .Y(_0695_)
  );
  sky130_fd_sc_hd__xor2_1 _1465_ (
    .A(_0682_),
    .B(_0683_),
    .X(_0696_)
  );
  sky130_fd_sc_hd__xnor2_1 _1466_ (
    .A(_0690_),
    .B(_0696_),
    .Y(_0697_)
  );
  sky130_fd_sc_hd__nor3_1 _1467_ (
    .A(_0685_),
    .B(_0690_),
    .C(_0696_),
    .Y(_0698_)
  );
  sky130_fd_sc_hd__nor2_1 _1468_ (
    .A(_0686_),
    .B(_0698_),
    .Y(_0699_)
  );
  sky130_fd_sc_hd__o31ai_1 _1469_ (
    .A1(_0687_),
    .A2(_0695_),
    .A3(_0697_),
    .B1(_0699_),
    .Y(_0700_)
  );
  sky130_fd_sc_hd__xor2_1 _1470_ (
    .A(_0675_),
    .B(_0676_),
    .X(_0701_)
  );
  sky130_fd_sc_hd__a21oi_1 _1471_ (
    .A1(_0700_),
    .A2(_0701_),
    .B1(_0677_),
    .Y(_0702_)
  );
  sky130_fd_sc_hd__nor2_1 _1472_ (
    .A(_0664_),
    .B(_0702_),
    .Y(_0703_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1473_ (
    .A(_0664_),
    .SLEEP(_0702_),
    .X(_0704_)
  );
  sky130_fd_sc_hd__o21ai_0 _1474_ (
    .A1(_0660_),
    .A2(_0661_),
    .B1(_0704_),
    .Y(_0705_)
  );
  sky130_fd_sc_hd__xor2_1 _1475_ (
    .A(_0647_),
    .B(_0648_),
    .X(_0706_)
  );
  sky130_fd_sc_hd__o21ai_0 _1476_ (
    .A1(_0662_),
    .A2(_0703_),
    .B1(_0706_),
    .Y(_0707_)
  );
  sky130_fd_sc_hd__nand2_1 _1477_ (
    .A(_0649_),
    .B(_0707_),
    .Y(_0708_)
  );
  sky130_fd_sc_hd__xor2_1 _1478_ (
    .A(_0634_),
    .B(_0635_),
    .X(_0709_)
  );
  sky130_fd_sc_hd__a21boi_0 _1479_ (
    .A1(_0649_),
    .A2(_0707_),
    .B1_N(_0709_),
    .Y(_0710_)
  );
  sky130_fd_sc_hd__xor2_1 _1480_ (
    .A(_0621_),
    .B(_0622_),
    .X(_0711_)
  );
  sky130_fd_sc_hd__o21ai_0 _1481_ (
    .A1(_0636_),
    .A2(_0710_),
    .B1(_0711_),
    .Y(_0712_)
  );
  sky130_fd_sc_hd__nand2_1 _1482_ (
    .A(_0623_),
    .B(_0712_),
    .Y(_0713_)
  );
  sky130_fd_sc_hd__xor2_1 _1483_ (
    .A(_0608_),
    .B(_0609_),
    .X(_0714_)
  );
  sky130_fd_sc_hd__a21boi_0 _1484_ (
    .A1(_0623_),
    .A2(_0712_),
    .B1_N(_0714_),
    .Y(_0715_)
  );
  sky130_fd_sc_hd__nor2_1 _1485_ (
    .A(_0610_),
    .B(_0715_),
    .Y(_0716_)
  );
  sky130_fd_sc_hd__nand2_1 _1486_ (
    .A(_0595_),
    .B(_0596_),
    .Y(_0717_)
  );
  sky130_fd_sc_hd__nand2_1 _1487_ (
    .A(_0597_),
    .B(_0717_),
    .Y(_0718_)
  );
  sky130_fd_sc_hd__o21bai_1 _1488_ (
    .A1(_0610_),
    .A2(_0715_),
    .B1_N(_0718_),
    .Y(_0719_)
  );
  sky130_fd_sc_hd__xnor2_1 _1489_ (
    .A(_0571_),
    .B(_0583_),
    .Y(_0720_)
  );
  sky130_fd_sc_hd__a21oi_1 _1490_ (
    .A1(_0597_),
    .A2(_0719_),
    .B1(_0720_),
    .Y(_0721_)
  );
  sky130_fd_sc_hd__nor2_1 _1491_ (
    .A(_0078_),
    .B(_0579_),
    .Y(_0722_)
  );
  sky130_fd_sc_hd__nand2_1 _1492_ (
    .A(_0568_),
    .B(_0722_),
    .Y(_0723_)
  );
  sky130_fd_sc_hd__o21ai_0 _1493_ (
    .A1(_0575_),
    .A2(_0580_),
    .B1(_0723_),
    .Y(_0724_)
  );
  sky130_fd_sc_hd__maj3_1 _1494_ (
    .A(_0089_),
    .B(_0576_),
    .C(_0577_),
    .X(_0725_)
  );
  sky130_fd_sc_hd__a21o_1 _1495_ (
    .A1(acc[29]),
    .A2(_0087_),
    .B1(_0085_),
    .X(_0726_)
  );
  sky130_fd_sc_hd__xnor2_1 _1496_ (
    .A(acc[30]),
    .B(_0087_),
    .Y(_0727_)
  );
  sky130_fd_sc_hd__xnor2_1 _1497_ (
    .A(_0089_),
    .B(_0727_),
    .Y(_0728_)
  );
  sky130_fd_sc_hd__xnor2_1 _1498_ (
    .A(_0726_),
    .B(_0728_),
    .Y(_0729_)
  );
  sky130_fd_sc_hd__o21ai_0 _1499_ (
    .A1(_0078_),
    .A2(_0579_),
    .B1(_0729_),
    .Y(_0730_)
  );
  sky130_fd_sc_hd__or3_1 _1500_ (
    .A(_0078_),
    .B(_0579_),
    .C(_0729_),
    .X(_0731_)
  );
  sky130_fd_sc_hd__nand2_1 _1501_ (
    .A(_0730_),
    .B(_0731_),
    .Y(_0732_)
  );
  sky130_fd_sc_hd__xnor2_1 _1502_ (
    .A(_0725_),
    .B(_0732_),
    .Y(_0733_)
  );
  sky130_fd_sc_hd__nand2_1 _1503_ (
    .A(_0724_),
    .B(_0733_),
    .Y(_0734_)
  );
  sky130_fd_sc_hd__xor2_1 _1504_ (
    .A(_0724_),
    .B(_0733_),
    .X(_0735_)
  );
  sky130_fd_sc_hd__nand2b_1 _1505_ (
    .A_N(_0582_),
    .B(_0735_),
    .Y(_0736_)
  );
  sky130_fd_sc_hd__xnor2_1 _1506_ (
    .A(_0582_),
    .B(_0735_),
    .Y(_0737_)
  );
  sky130_fd_sc_hd__or3_1 _1507_ (
    .A(_0584_),
    .B(_0721_),
    .C(_0737_),
    .X(_0738_)
  );
  sky130_fd_sc_hd__o21ai_0 _1508_ (
    .A1(_0584_),
    .A2(_0721_),
    .B1(_0737_),
    .Y(_0739_)
  );
  sky130_fd_sc_hd__nand2_1 _1509_ (
    .A(_0738_),
    .B(_0739_),
    .Y(_0740_)
  );
  sky130_fd_sc_hd__o21ai_0 _1510_ (
    .A1(\core.valid_q ),
    .A2(acc[30]),
    .B1(_0480_),
    .Y(_0741_)
  );
  sky130_fd_sc_hd__a21oi_1 _1511_ (
    .A1(\core.valid_q ),
    .A2(_0740_),
    .B1(_0741_),
    .Y(_0033_)
  );
  sky130_fd_sc_hd__nand3_1 _1512_ (
    .A(_0597_),
    .B(_0719_),
    .C(_0720_),
    .Y(_0742_)
  );
  sky130_fd_sc_hd__nand2b_1 _1513_ (
    .A_N(_0721_),
    .B(_0742_),
    .Y(_0743_)
  );
  sky130_fd_sc_hd__o21ai_0 _1514_ (
    .A1(\core.valid_q ),
    .A2(acc[29]),
    .B1(_0480_),
    .Y(_0744_)
  );
  sky130_fd_sc_hd__a21oi_1 _1515_ (
    .A1(\core.valid_q ),
    .A2(_0743_),
    .B1(_0744_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__nand2_1 _1516_ (
    .A(_0716_),
    .B(_0718_),
    .Y(_0745_)
  );
  sky130_fd_sc_hd__nand2_1 _1517_ (
    .A(_0719_),
    .B(_0745_),
    .Y(_0746_)
  );
  sky130_fd_sc_hd__o21ai_0 _1518_ (
    .A1(\core.valid_q ),
    .A2(acc[28]),
    .B1(_0480_),
    .Y(_0747_)
  );
  sky130_fd_sc_hd__a21oi_1 _1519_ (
    .A1(\core.valid_q ),
    .A2(_0746_),
    .B1(_0747_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__xnor2_1 _1520_ (
    .A(_0713_),
    .B(_0714_),
    .Y(_0748_)
  );
  sky130_fd_sc_hd__o21ai_0 _1521_ (
    .A1(\core.valid_q ),
    .A2(acc[27]),
    .B1(_0480_),
    .Y(_0749_)
  );
  sky130_fd_sc_hd__a21oi_1 _1522_ (
    .A1(\core.valid_q ),
    .A2(_0748_),
    .B1(_0749_),
    .Y(_0036_)
  );
  sky130_fd_sc_hd__or3_1 _1523_ (
    .A(_0636_),
    .B(_0710_),
    .C(_0711_),
    .X(_0750_)
  );
  sky130_fd_sc_hd__nand2_1 _1524_ (
    .A(_0712_),
    .B(_0750_),
    .Y(_0751_)
  );
  sky130_fd_sc_hd__o21ai_0 _1525_ (
    .A1(\core.valid_q ),
    .A2(acc[26]),
    .B1(_0480_),
    .Y(_0752_)
  );
  sky130_fd_sc_hd__a21oi_1 _1526_ (
    .A1(\core.valid_q ),
    .A2(_0751_),
    .B1(_0752_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__xnor2_1 _1527_ (
    .A(_0708_),
    .B(_0709_),
    .Y(_0753_)
  );
  sky130_fd_sc_hd__o21ai_0 _1528_ (
    .A1(\core.valid_q ),
    .A2(acc[25]),
    .B1(_0480_),
    .Y(_0754_)
  );
  sky130_fd_sc_hd__a21oi_1 _1529_ (
    .A1(\core.valid_q ),
    .A2(_0753_),
    .B1(_0754_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__xnor2_1 _1530_ (
    .A(_0705_),
    .B(_0706_),
    .Y(_0755_)
  );
  sky130_fd_sc_hd__o21ai_0 _1531_ (
    .A1(\core.valid_q ),
    .A2(acc[24]),
    .B1(_0480_),
    .Y(_0756_)
  );
  sky130_fd_sc_hd__a21oi_1 _1532_ (
    .A1(\core.valid_q ),
    .A2(_0755_),
    .B1(_0756_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__nand2_1 _1533_ (
    .A(_0664_),
    .B(_0702_),
    .Y(_0757_)
  );
  sky130_fd_sc_hd__a21oi_1 _1534_ (
    .A1(_0704_),
    .A2(_0757_),
    .B1(_0052_),
    .Y(_0758_)
  );
  sky130_fd_sc_hd__o21ai_0 _1535_ (
    .A1(\core.valid_q ),
    .A2(acc[23]),
    .B1(_0480_),
    .Y(_0759_)
  );
  sky130_fd_sc_hd__nor2_1 _1536_ (
    .A(_0758_),
    .B(_0759_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__xnor2_1 _1537_ (
    .A(_0700_),
    .B(_0701_),
    .Y(_0760_)
  );
  sky130_fd_sc_hd__o21ai_0 _1538_ (
    .A1(\core.valid_q ),
    .A2(acc[22]),
    .B1(_0480_),
    .Y(_0761_)
  );
  sky130_fd_sc_hd__a21oi_1 _1539_ (
    .A1(\core.valid_q ),
    .A2(_0760_),
    .B1(_0761_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__maj3_1 _1540_ (
    .A(_0690_),
    .B(_0695_),
    .C(_0696_),
    .X(_0762_)
  );
  sky130_fd_sc_hd__xnor2_1 _1541_ (
    .A(_0687_),
    .B(_0762_),
    .Y(_0763_)
  );
  sky130_fd_sc_hd__o21ai_0 _1542_ (
    .A1(\core.valid_q ),
    .A2(acc[21]),
    .B1(_0480_),
    .Y(_0764_)
  );
  sky130_fd_sc_hd__a21oi_1 _1543_ (
    .A1(\core.valid_q ),
    .A2(_0763_),
    .B1(_0764_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__nor2_1 _1544_ (
    .A(_0051_),
    .B(_0481_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__o21ai_0 _1545_ (
    .A1(_0051_),
    .A2(b[7]),
    .B1(_0480_),
    .Y(_0765_)
  );
  sky130_fd_sc_hd__nor2_1 _1546_ (
    .A(valid),
    .B(\core.b_q [7]),
    .Y(_0766_)
  );
  sky130_fd_sc_hd__nor2_1 _1547_ (
    .A(_0765_),
    .B(_0766_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__xnor2_1 _1548_ (
    .A(_0695_),
    .B(_0697_),
    .Y(_0767_)
  );
  sky130_fd_sc_hd__o21ai_0 _1549_ (
    .A1(\core.valid_q ),
    .A2(acc[20]),
    .B1(_0480_),
    .Y(_0768_)
  );
  sky130_fd_sc_hd__a21oi_1 _1550_ (
    .A1(\core.valid_q ),
    .A2(_0767_),
    .B1(_0768_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__a21o_1 _1551_ (
    .A1(_0475_),
    .A2(_0478_),
    .B1(_0693_),
    .X(_0769_)
  );
  sky130_fd_sc_hd__a31oi_1 _1552_ (
    .A1(_0475_),
    .A2(_0478_),
    .A3(_0693_),
    .B1(_0052_),
    .Y(_0770_)
  );
  sky130_fd_sc_hd__o21ai_0 _1553_ (
    .A1(\core.valid_q ),
    .A2(acc[19]),
    .B1(_0480_),
    .Y(_0771_)
  );
  sky130_fd_sc_hd__a21oi_1 _1554_ (
    .A1(_0769_),
    .A2(_0770_),
    .B1(_0771_),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__xnor2_1 _1555_ (
    .A(acc[31]),
    .B(_0087_),
    .Y(_0772_)
  );
  sky130_fd_sc_hd__mux2i_1 _1556_ (
    .A0(_0089_),
    .A1(_0727_),
    .S(_0726_),
    .Y(_0773_)
  );
  sky130_fd_sc_hd__o21ai_0 _1557_ (
    .A1(_0089_),
    .A2(_0727_),
    .B1(_0773_),
    .Y(_0774_)
  );
  sky130_fd_sc_hd__a21oi_1 _1558_ (
    .A1(acc[30]),
    .A2(_0087_),
    .B1(_0085_),
    .Y(_0775_)
  );
  sky130_fd_sc_hd__xnor2_1 _1559_ (
    .A(_0772_),
    .B(_0775_),
    .Y(_0776_)
  );
  sky130_fd_sc_hd__xnor2_1 _1560_ (
    .A(_0774_),
    .B(_0776_),
    .Y(_0777_)
  );
  sky130_fd_sc_hd__mux2i_1 _1561_ (
    .A0(_0730_),
    .A1(_0731_),
    .S(_0725_),
    .Y(_0778_)
  );
  sky130_fd_sc_hd__xnor2_1 _1562_ (
    .A(_0777_),
    .B(_0778_),
    .Y(_0779_)
  );
  sky130_fd_sc_hd__xnor2_1 _1563_ (
    .A(_0734_),
    .B(_0779_),
    .Y(_0780_)
  );
  sky130_fd_sc_hd__a21o_1 _1564_ (
    .A1(_0736_),
    .A2(_0739_),
    .B1(_0780_),
    .X(_0781_)
  );
  sky130_fd_sc_hd__nand3_1 _1565_ (
    .A(_0736_),
    .B(_0739_),
    .C(_0780_),
    .Y(_0782_)
  );
  sky130_fd_sc_hd__o21ai_0 _1566_ (
    .A1(acc[31]),
    .A2(\core.valid_q ),
    .B1(_0480_),
    .Y(_0783_)
  );
  sky130_fd_sc_hd__a31oi_1 _1567_ (
    .A1(\core.valid_q ),
    .A2(_0781_),
    .A3(_0782_),
    .B1(_0783_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__o21ai_0 _1568_ (
    .A1(a[7]),
    .A2(_0051_),
    .B1(_0480_),
    .Y(_0784_)
  );
  sky130_fd_sc_hd__a21oi_1 _1569_ (
    .A1(_0050_),
    .A2(_0051_),
    .B1(_0784_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__dfxtp_1 _1570_ (
    .CLK(clk),
    .D(_0043_),
    .Q(\core.valid_q )
  );
  sky130_fd_sc_hd__dfxtp_1 _1571_ (
    .CLK(clk),
    .D(_0025_),
    .Q(\core.b_q [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1572_ (
    .CLK(clk),
    .D(_0024_),
    .Q(\core.b_q [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _1573_ (
    .CLK(clk),
    .D(_0023_),
    .Q(\core.b_q [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _1574_ (
    .CLK(clk),
    .D(_0022_),
    .Q(\core.b_q [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _1575_ (
    .CLK(clk),
    .D(_0021_),
    .Q(\core.b_q [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _1576_ (
    .CLK(clk),
    .D(_0020_),
    .Q(\core.b_q [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _1577_ (
    .CLK(clk),
    .D(_0019_),
    .Q(\core.b_q [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _1578_ (
    .CLK(clk),
    .D(_0044_),
    .Q(\core.b_q [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _1579_ (
    .CLK(clk),
    .D(_0018_),
    .Q(acc[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1580_ (
    .CLK(clk),
    .D(_0017_),
    .Q(acc[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _1581_ (
    .CLK(clk),
    .D(_0016_),
    .Q(acc[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _1582_ (
    .CLK(clk),
    .D(_0015_),
    .Q(acc[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _1583_ (
    .CLK(clk),
    .D(_0014_),
    .Q(acc[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _1584_ (
    .CLK(clk),
    .D(_0013_),
    .Q(acc[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _1585_ (
    .CLK(clk),
    .D(_0012_),
    .Q(acc[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _1586_ (
    .CLK(clk),
    .D(_0011_),
    .Q(acc[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _1587_ (
    .CLK(clk),
    .D(_0010_),
    .Q(acc[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _1588_ (
    .CLK(clk),
    .D(_0009_),
    .Q(acc[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _1589_ (
    .CLK(clk),
    .D(_0008_),
    .Q(acc[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _1590_ (
    .CLK(clk),
    .D(_0007_),
    .Q(acc[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _1591_ (
    .CLK(clk),
    .D(_0006_),
    .Q(acc[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _1592_ (
    .CLK(clk),
    .D(_0005_),
    .Q(acc[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _1593_ (
    .CLK(clk),
    .D(_0004_),
    .Q(acc[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _1594_ (
    .CLK(clk),
    .D(_0003_),
    .Q(acc[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _1595_ (
    .CLK(clk),
    .D(_0002_),
    .Q(acc[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _1596_ (
    .CLK(clk),
    .D(_0001_),
    .Q(acc[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _1597_ (
    .CLK(clk),
    .D(_0000_),
    .Q(acc[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _1598_ (
    .CLK(clk),
    .D(_0046_),
    .Q(acc[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _1599_ (
    .CLK(clk),
    .D(_0045_),
    .Q(acc[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _1600_ (
    .CLK(clk),
    .D(_0042_),
    .Q(acc[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _1601_ (
    .CLK(clk),
    .D(_0041_),
    .Q(acc[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _1602_ (
    .CLK(clk),
    .D(_0040_),
    .Q(acc[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _1603_ (
    .CLK(clk),
    .D(_0039_),
    .Q(acc[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _1604_ (
    .CLK(clk),
    .D(_0038_),
    .Q(acc[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _1605_ (
    .CLK(clk),
    .D(_0037_),
    .Q(acc[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _1606_ (
    .CLK(clk),
    .D(_0036_),
    .Q(acc[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _1607_ (
    .CLK(clk),
    .D(_0035_),
    .Q(acc[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _1608_ (
    .CLK(clk),
    .D(_0034_),
    .Q(acc[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _1609_ (
    .CLK(clk),
    .D(_0033_),
    .Q(acc[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _1610_ (
    .CLK(clk),
    .D(_0047_),
    .Q(acc[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _1611_ (
    .CLK(clk),
    .D(_0048_),
    .Q(out_valid)
  );
  sky130_fd_sc_hd__dfxtp_1 _1612_ (
    .CLK(clk),
    .D(_0032_),
    .Q(\core.a_q [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1613_ (
    .CLK(clk),
    .D(_0031_),
    .Q(\core.a_q [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _1614_ (
    .CLK(clk),
    .D(_0030_),
    .Q(\core.a_q [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _1615_ (
    .CLK(clk),
    .D(_0029_),
    .Q(\core.a_q [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _1616_ (
    .CLK(clk),
    .D(_0028_),
    .Q(\core.a_q [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _1617_ (
    .CLK(clk),
    .D(_0027_),
    .Q(\core.a_q [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _1618_ (
    .CLK(clk),
    .D(_0026_),
    .Q(\core.a_q [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _1619_ (
    .CLK(clk),
    .D(_0049_),
    .Q(\core.a_q [7])
  );
endmodule
