/* Generated by Yosys 0.69+ (git sha1 20091e4ca, Release, GNU /usr/bin/c++ 11.4.0) [github.com/The-OpenROAD-Project/yosys at master] */

module mac_b2(clk, rst, clear, valid, a, b, acc, out_valid);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input clear;
  wire clear;
  input valid;
  wire valid;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [31:0] acc;
  wire [31:0] acc;
  output out_valid;
  wire out_valid;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire [7:0] \core.a_q ;
  wire [7:0] \core.b_q ;
  wire \core.valid_q ;
  wire \core.zero_q ;
  sky130_fd_sc_hd__clkinv_1 _0743_ (
    .A(acc[1]),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__clkinv_1 _0744_ (
    .A(acc[3]),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__clkinv_1 _0745_ (
    .A(acc[4]),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__clkinv_1 _0746_ (
    .A(acc[5]),
    .Y(_0054_)
  );
  sky130_fd_sc_hd__clkinv_1 _0747_ (
    .A(\core.a_q [7]),
    .Y(_0055_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0748_ (
    .A(\core.valid_q ),
    .SLEEP(\core.zero_q ),
    .X(_0056_)
  );
  sky130_fd_sc_hd__nand2b_1 _0749_ (
    .A_N(\core.zero_q ),
    .B(\core.valid_q ),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__nand2b_1 _0750_ (
    .A_N(\core.a_q [2]),
    .B(\core.b_q [7]),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__nand2_1 _0751_ (
    .A(\core.b_q [6]),
    .B(\core.a_q [3]),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__nand2_1 _0752_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [4]),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__xnor2_1 _0753_ (
    .A(_0058_),
    .B(_0059_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__maj3_1 _0754_ (
    .A(_0058_),
    .B(_0059_),
    .C(_0060_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__nand2_1 _0755_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [5]),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__nand2b_1 _0756_ (
    .A_N(\core.a_q [3]),
    .B(\core.b_q [7]),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__nand2_1 _0757_ (
    .A(\core.b_q [6]),
    .B(\core.a_q [4]),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__xnor2_1 _0758_ (
    .A(_0064_),
    .B(_0065_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__xor2_1 _0759_ (
    .A(_0063_),
    .B(_0066_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0760_ (
    .A(_0067_),
    .SLEEP(_0062_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__nand2_1 _0761_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [2]),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__nand2_1 _0762_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [3]),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__nand2_1 _0763_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [6]),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__nand2_1 _0764_ (
    .A(\core.b_q [3]),
    .B(\core.a_q [6]),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__xor2_1 _0765_ (
    .A(_0070_),
    .B(_0071_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__xnor2_1 _0766_ (
    .A(_0069_),
    .B(_0073_),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__xnor2_1 _0767_ (
    .A(_0062_),
    .B(_0067_),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__a21oi_1 _0768_ (
    .A1(_0074_),
    .A2(_0075_),
    .B1(_0068_),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__o21ai_0 _0769_ (
    .A1(\core.b_q [3]),
    .A2(\core.b_q [4]),
    .B1(\core.a_q [7]),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__and3_1 _0770_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [3]),
    .C(\core.b_q [4]),
    .X(_0078_)
  );
  sky130_fd_sc_hd__nor2_1 _0771_ (
    .A(_0077_),
    .B(_0078_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__xnor2_1 _0772_ (
    .A(_0069_),
    .B(_0079_),
    .Y(_0080_)
  );
  sky130_fd_sc_hd__xor2_1 _0773_ (
    .A(_0069_),
    .B(_0079_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__maj3_1 _0774_ (
    .A(_0063_),
    .B(_0064_),
    .C(_0065_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__nand2_1 _0775_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [6]),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__nand2b_1 _0776_ (
    .A_N(\core.a_q [4]),
    .B(\core.b_q [7]),
    .Y(_0084_)
  );
  sky130_fd_sc_hd__nand2_1 _0777_ (
    .A(\core.b_q [6]),
    .B(\core.a_q [5]),
    .Y(_0085_)
  );
  sky130_fd_sc_hd__xnor2_1 _0778_ (
    .A(_0084_),
    .B(_0085_),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__xor2_1 _0779_ (
    .A(_0083_),
    .B(_0086_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0780_ (
    .A(_0087_),
    .SLEEP(_0082_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__xnor2_1 _0781_ (
    .A(_0082_),
    .B(_0087_),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__xnor2_1 _0782_ (
    .A(_0080_),
    .B(_0089_),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__nor2_1 _0783_ (
    .A(_0076_),
    .B(_0090_),
    .Y(_0091_)
  );
  sky130_fd_sc_hd__and2_0 _0784_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [0]),
    .X(_0092_)
  );
  sky130_fd_sc_hd__and3_1 _0785_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [7]),
    .C(\core.b_q [0]),
    .X(_0093_)
  );
  sky130_fd_sc_hd__o21ai_0 _0786_ (
    .A1(\core.b_q [1]),
    .A2(\core.b_q [0]),
    .B1(\core.a_q [7]),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__a21oi_1 _0787_ (
    .A1(\core.b_q [1]),
    .A2(\core.b_q [0]),
    .B1(_0094_),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__a21oi_1 _0788_ (
    .A1(acc[10]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__maj3_1 _0789_ (
    .A(_0069_),
    .B(_0070_),
    .C(_0071_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__xnor2_1 _0790_ (
    .A(acc[11]),
    .B(_0095_),
    .Y(_0098_)
  );
  sky130_fd_sc_hd__xor2_1 _0791_ (
    .A(_0097_),
    .B(_0098_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__xnor2_1 _0792_ (
    .A(_0096_),
    .B(_0099_),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__xor2_1 _0793_ (
    .A(_0076_),
    .B(_0090_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__a21oi_1 _0794_ (
    .A1(_0100_),
    .A2(_0101_),
    .B1(_0091_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__a21oi_1 _0795_ (
    .A1(acc[11]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__a31oi_1 _0796_ (
    .A1(\core.a_q [7]),
    .A2(\core.b_q [2]),
    .A3(_0079_),
    .B1(_0078_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__xnor2_1 _0797_ (
    .A(acc[12]),
    .B(_0095_),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__xor2_1 _0798_ (
    .A(_0104_),
    .B(_0105_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__xnor2_1 _0799_ (
    .A(_0103_),
    .B(_0106_),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__a21oi_1 _0800_ (
    .A1(_0080_),
    .A2(_0089_),
    .B1(_0088_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__maj3_1 _0801_ (
    .A(_0083_),
    .B(_0084_),
    .C(_0085_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__nand2_1 _0802_ (
    .A(\core.a_q [7]),
    .B(\core.b_q [5]),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__nand2b_1 _0803_ (
    .A_N(\core.a_q [5]),
    .B(\core.b_q [7]),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__nand2_1 _0804_ (
    .A(\core.b_q [6]),
    .B(\core.a_q [6]),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__xnor2_1 _0805_ (
    .A(_0111_),
    .B(_0112_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__xnor2_1 _0806_ (
    .A(_0110_),
    .B(_0113_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__nor2_1 _0807_ (
    .A(_0109_),
    .B(_0114_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__xor2_1 _0808_ (
    .A(_0109_),
    .B(_0114_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__xnor2_1 _0809_ (
    .A(_0081_),
    .B(_0116_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__nand2b_1 _0810_ (
    .A_N(_0108_),
    .B(_0117_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__xnor2_1 _0811_ (
    .A(_0108_),
    .B(_0117_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__nand2_1 _0812_ (
    .A(_0107_),
    .B(_0119_),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__xnor2_1 _0813_ (
    .A(_0107_),
    .B(_0119_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__maj3_1 _0814_ (
    .A(_0096_),
    .B(_0097_),
    .C(_0098_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__xor2_1 _0815_ (
    .A(_0102_),
    .B(_0121_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__maj3_1 _0816_ (
    .A(_0102_),
    .B(_0121_),
    .C(_0122_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__maj3_1 _0817_ (
    .A(_0103_),
    .B(_0104_),
    .C(_0105_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__a21oi_1 _0818_ (
    .A1(acc[12]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__xnor2_1 _0819_ (
    .A(acc[13]),
    .B(_0095_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__xor2_1 _0820_ (
    .A(_0104_),
    .B(_0127_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__xnor2_1 _0821_ (
    .A(_0126_),
    .B(_0128_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__a21oi_1 _0822_ (
    .A1(_0080_),
    .A2(_0116_),
    .B1(_0115_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__maj3_1 _0823_ (
    .A(_0110_),
    .B(_0111_),
    .C(_0112_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__nand2b_1 _0824_ (
    .A_N(\core.a_q [6]),
    .B(\core.b_q [7]),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__o21ai_0 _0825_ (
    .A1(\core.b_q [6]),
    .A2(\core.b_q [5]),
    .B1(\core.a_q [7]),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__a21o_1 _0826_ (
    .A1(\core.b_q [6]),
    .A2(\core.b_q [5]),
    .B1(_0133_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__nor2_1 _0827_ (
    .A(_0132_),
    .B(_0134_),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__xnor2_1 _0828_ (
    .A(_0132_),
    .B(_0134_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__xor2_1 _0829_ (
    .A(_0131_),
    .B(_0136_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__xnor2_1 _0830_ (
    .A(_0081_),
    .B(_0137_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__nand2b_1 _0831_ (
    .A_N(_0130_),
    .B(_0138_),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__xnor2_1 _0832_ (
    .A(_0130_),
    .B(_0138_),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__nand2_1 _0833_ (
    .A(_0129_),
    .B(_0140_),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__xnor2_1 _0834_ (
    .A(_0129_),
    .B(_0140_),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__a21oi_1 _0835_ (
    .A1(_0118_),
    .A2(_0120_),
    .B1(_0142_),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__nand3_1 _0836_ (
    .A(_0118_),
    .B(_0120_),
    .C(_0142_),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__nand2b_1 _0837_ (
    .A_N(_0143_),
    .B(_0144_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__nor2_1 _0838_ (
    .A(_0125_),
    .B(_0145_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__xor2_1 _0839_ (
    .A(_0125_),
    .B(_0145_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0840_ (
    .A(_0147_),
    .SLEEP(_0124_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__maj3_1 _0841_ (
    .A(_0104_),
    .B(_0126_),
    .C(_0127_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__a21oi_1 _0842_ (
    .A1(acc[13]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__xnor2_1 _0843_ (
    .A(acc[14]),
    .B(_0095_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__xor2_1 _0844_ (
    .A(_0104_),
    .B(_0151_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__xnor2_1 _0845_ (
    .A(_0150_),
    .B(_0152_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__maj3_1 _0846_ (
    .A(_0081_),
    .B(_0131_),
    .C(_0136_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__a21boi_0 _0847_ (
    .A1(_0055_),
    .A2(\core.b_q [7]),
    .B1_N(_0133_),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__and2_0 _0848_ (
    .A(_0081_),
    .B(_0155_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__clkinv_1 _0849_ (
    .A(_0156_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__nor3_1 _0850_ (
    .A(_0080_),
    .B(_0132_),
    .C(_0134_),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__nor2_1 _0851_ (
    .A(_0156_),
    .B(_0158_),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__or3_1 _0852_ (
    .A(_0081_),
    .B(_0135_),
    .C(_0155_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__nand2_1 _0853_ (
    .A(_0159_),
    .B(_0160_),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0854_ (
    .A(_0154_),
    .SLEEP(_0161_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__xor2_1 _0855_ (
    .A(_0154_),
    .B(_0161_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__nand2_1 _0856_ (
    .A(_0153_),
    .B(_0163_),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__xnor2_1 _0857_ (
    .A(_0153_),
    .B(_0163_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__a21oi_1 _0858_ (
    .A1(_0139_),
    .A2(_0141_),
    .B1(_0165_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__nand3_1 _0859_ (
    .A(_0139_),
    .B(_0141_),
    .C(_0165_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__nand2b_1 _0860_ (
    .A_N(_0166_),
    .B(_0167_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__nor2_1 _0861_ (
    .A(_0149_),
    .B(_0168_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__xor2_1 _0862_ (
    .A(_0149_),
    .B(_0168_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__o21a_1 _0863_ (
    .A1(_0143_),
    .A2(_0146_),
    .B1(_0170_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__nor3_1 _0864_ (
    .A(_0143_),
    .B(_0146_),
    .C(_0170_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0865_ (
    .A(_0171_),
    .SLEEP(_0172_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__clkinv_1 _0866_ (
    .A(_0173_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nand2_1 _0867_ (
    .A(_0148_),
    .B(_0174_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nand2b_1 _0868_ (
    .A_N(\core.a_q [1]),
    .B(\core.b_q [7]),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nand2_1 _0869_ (
    .A(\core.b_q [6]),
    .B(\core.a_q [2]),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nand2_1 _0870_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [3]),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__xnor2_1 _0871_ (
    .A(_0176_),
    .B(_0177_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__maj3_1 _0872_ (
    .A(_0176_),
    .B(_0177_),
    .C(_0178_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__xnor2_1 _0873_ (
    .A(_0060_),
    .B(_0061_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__nand2_1 _0874_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [5]),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__nand2_1 _0875_ (
    .A(\core.b_q [3]),
    .B(\core.a_q [5]),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__xnor2_1 _0876_ (
    .A(_0072_),
    .B(_0182_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__xnor2_1 _0877_ (
    .A(_0069_),
    .B(_0184_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__maj3_1 _0878_ (
    .A(_0180_),
    .B(_0181_),
    .C(_0185_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__clkinv_1 _0879_ (
    .A(_0186_),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__xor2_1 _0880_ (
    .A(_0074_),
    .B(_0075_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__a21oi_1 _0881_ (
    .A1(acc[9]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__maj3_1 _0882_ (
    .A(_0069_),
    .B(_0072_),
    .C(_0182_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__xnor2_1 _0883_ (
    .A(acc[10]),
    .B(_0095_),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__xor2_1 _0884_ (
    .A(_0190_),
    .B(_0191_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__xnor2_1 _0885_ (
    .A(_0189_),
    .B(_0192_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__xor2_1 _0886_ (
    .A(_0186_),
    .B(_0188_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__maj3_1 _0887_ (
    .A(_0187_),
    .B(_0188_),
    .C(_0193_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__xor2_1 _0888_ (
    .A(_0100_),
    .B(_0101_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__and2_0 _0889_ (
    .A(_0195_),
    .B(_0196_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__maj3_1 _0890_ (
    .A(_0189_),
    .B(_0190_),
    .C(_0191_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__nor2_1 _0891_ (
    .A(_0195_),
    .B(_0196_),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__nor2_1 _0892_ (
    .A(_0197_),
    .B(_0199_),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__nor3_1 _0893_ (
    .A(_0197_),
    .B(_0198_),
    .C(_0199_),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__xnor2_1 _0894_ (
    .A(_0122_),
    .B(_0123_),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__o21ai_0 _0895_ (
    .A1(_0197_),
    .A2(_0201_),
    .B1(_0202_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__xor2_1 _0896_ (
    .A(_0124_),
    .B(_0147_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__nor2_1 _0897_ (
    .A(_0203_),
    .B(_0204_),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__nand2b_1 _0898_ (
    .A_N(\core.a_q [0]),
    .B(\core.b_q [7]),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__nand2_1 _0899_ (
    .A(\core.b_q [6]),
    .B(\core.a_q [1]),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__nand2_1 _0900_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [2]),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__xor2_1 _0901_ (
    .A(_0206_),
    .B(_0207_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__maj3_1 _0902_ (
    .A(_0206_),
    .B(_0207_),
    .C(_0208_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__xnor2_1 _0903_ (
    .A(_0178_),
    .B(_0179_),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__nand2_1 _0904_ (
    .A(\core.b_q [2]),
    .B(\core.a_q [6]),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__nand2_1 _0905_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [4]),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__nand2_1 _0906_ (
    .A(\core.b_q [3]),
    .B(\core.a_q [4]),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__xnor2_1 _0907_ (
    .A(_0183_),
    .B(_0213_),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__xnor2_1 _0908_ (
    .A(_0212_),
    .B(_0215_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__maj3_1 _0909_ (
    .A(_0210_),
    .B(_0211_),
    .C(_0216_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__xnor3_1 _0910_ (
    .A(_0180_),
    .B(_0181_),
    .C(_0185_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__nand2b_1 _0911_ (
    .A_N(_0217_),
    .B(_0218_),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__a21oi_1 _0912_ (
    .A1(acc[8]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__maj3_1 _0913_ (
    .A(_0183_),
    .B(_0212_),
    .C(_0213_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__xnor2_1 _0914_ (
    .A(acc[9]),
    .B(_0095_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__xor2_1 _0915_ (
    .A(_0221_),
    .B(_0222_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__xnor2_1 _0916_ (
    .A(_0220_),
    .B(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__xnor2_1 _0917_ (
    .A(_0217_),
    .B(_0218_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__nand2_1 _0918_ (
    .A(_0224_),
    .B(_0225_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__nand2_1 _0919_ (
    .A(_0219_),
    .B(_0226_),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__xnor2_1 _0920_ (
    .A(_0193_),
    .B(_0194_),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__maj3_1 _0921_ (
    .A(_0220_),
    .B(_0221_),
    .C(_0222_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__xor2_1 _0922_ (
    .A(_0227_),
    .B(_0228_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0923_ (
    .A(_0230_),
    .SLEEP(_0229_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__a21oi_1 _0924_ (
    .A1(_0227_),
    .A2(_0228_),
    .B1(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__xor2_1 _0925_ (
    .A(_0198_),
    .B(_0200_),
    .X(_0233_)
  );
  sky130_fd_sc_hd__nor2_1 _0926_ (
    .A(_0232_),
    .B(_0233_),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__or3_1 _0927_ (
    .A(_0197_),
    .B(_0201_),
    .C(_0202_),
    .X(_0235_)
  );
  sky130_fd_sc_hd__nand2_1 _0928_ (
    .A(_0203_),
    .B(_0235_),
    .Y(_0236_)
  );
  sky130_fd_sc_hd__or3_1 _0929_ (
    .A(_0232_),
    .B(_0233_),
    .C(_0236_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__nand2_1 _0930_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [0]),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__nor2_1 _0931_ (
    .A(_0207_),
    .B(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__xnor2_1 _0932_ (
    .A(_0208_),
    .B(_0209_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__nand2_1 _0933_ (
    .A(\core.b_q [2]),
    .B(\core.a_q [5]),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__nand2_1 _0934_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [3]),
    .Y(_0242_)
  );
  sky130_fd_sc_hd__nand2_1 _0935_ (
    .A(\core.b_q [3]),
    .B(\core.a_q [3]),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__xor2_1 _0936_ (
    .A(_0214_),
    .B(_0242_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__xnor2_1 _0937_ (
    .A(_0241_),
    .B(_0244_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__maj3_1 _0938_ (
    .A(_0239_),
    .B(_0240_),
    .C(_0245_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__xnor3_1 _0939_ (
    .A(_0210_),
    .B(_0211_),
    .C(_0216_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__nand2_1 _0940_ (
    .A(_0246_),
    .B(_0247_),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__and2_0 _0941_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [6]),
    .X(_0249_)
  );
  sky130_fd_sc_hd__maj3_1 _0942_ (
    .A(\core.b_q [7]),
    .B(_0092_),
    .C(_0249_),
    .X(_0250_)
  );
  sky130_fd_sc_hd__maj3_1 _0943_ (
    .A(_0214_),
    .B(_0241_),
    .C(_0242_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__xnor2_1 _0944_ (
    .A(acc[8]),
    .B(_0095_),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__nor2_1 _0945_ (
    .A(_0251_),
    .B(_0252_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__xor2_1 _0946_ (
    .A(_0251_),
    .B(_0252_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__xnor2_1 _0947_ (
    .A(_0250_),
    .B(_0254_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__xnor2_1 _0948_ (
    .A(_0246_),
    .B(_0247_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__o21ai_0 _0949_ (
    .A1(_0255_),
    .A2(_0256_),
    .B1(_0248_),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__xor2_1 _0950_ (
    .A(_0224_),
    .B(_0225_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__nand2_1 _0951_ (
    .A(_0257_),
    .B(_0258_),
    .Y(_0259_)
  );
  sky130_fd_sc_hd__a21oi_1 _0952_ (
    .A1(_0250_),
    .A2(_0254_),
    .B1(_0253_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__xnor2_1 _0953_ (
    .A(_0257_),
    .B(_0258_),
    .Y(_0261_)
  );
  sky130_fd_sc_hd__o21ai_0 _0954_ (
    .A1(_0260_),
    .A2(_0261_),
    .B1(_0259_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__xor2_1 _0955_ (
    .A(_0229_),
    .B(_0230_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__nand2b_1 _0956_ (
    .A_N(_0263_),
    .B(_0262_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__xor2_1 _0957_ (
    .A(_0232_),
    .B(_0233_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__nor2b_1 _0958_ (
    .A(_0264_),
    .B_N(_0265_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__nand2_1 _0959_ (
    .A(\core.b_q [2]),
    .B(\core.a_q [4]),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nand2_1 _0960_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [2]),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nand2_1 _0961_ (
    .A(\core.b_q [3]),
    .B(\core.a_q [2]),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__xor2_1 _0962_ (
    .A(_0243_),
    .B(_0268_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__xnor2_1 _0963_ (
    .A(_0267_),
    .B(_0270_),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__a22oi_1 _0964_ (
    .A1(\core.b_q [5]),
    .A2(\core.a_q [1]),
    .B1(\core.a_q [0]),
    .B2(\core.b_q [6]),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__nor2_1 _0965_ (
    .A(_0239_),
    .B(_0272_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__and2_0 _0966_ (
    .A(_0271_),
    .B(_0273_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__xor3_1 _0967_ (
    .A(_0239_),
    .B(_0240_),
    .C(_0245_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__nand2_1 _0968_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [6]),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__nand2_1 _0969_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [5]),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__nand2_1 _0970_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [5]),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__nand2_1 _0971_ (
    .A(_0276_),
    .B(_0277_),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__a32o_1 _0972_ (
    .A1(\core.b_q [0]),
    .A2(\core.a_q [5]),
    .A3(_0249_),
    .B1(_0279_),
    .B2(acc[6]),
    .X(_0280_)
  );
  sky130_fd_sc_hd__maj3_1 _0973_ (
    .A(_0243_),
    .B(_0267_),
    .C(_0268_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__xnor3_1 _0974_ (
    .A(\core.b_q [7]),
    .B(_0092_),
    .C(_0249_),
    .X(_0282_)
  );
  sky130_fd_sc_hd__xor2_1 _0975_ (
    .A(_0281_),
    .B(_0282_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__nand2_1 _0976_ (
    .A(_0280_),
    .B(_0283_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__xor2_1 _0977_ (
    .A(_0280_),
    .B(_0283_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__maj3_1 _0978_ (
    .A(_0274_),
    .B(_0275_),
    .C(_0285_),
    .X(_0286_)
  );
  sky130_fd_sc_hd__xor2_1 _0979_ (
    .A(_0255_),
    .B(_0256_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__o21ai_0 _0980_ (
    .A1(_0281_),
    .A2(_0282_),
    .B1(_0284_),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__xnor3_1 _0981_ (
    .A(_0255_),
    .B(_0256_),
    .C(_0286_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0982_ (
    .A(_0288_),
    .SLEEP(_0289_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__a21oi_1 _0983_ (
    .A1(_0286_),
    .A2(_0287_),
    .B1(_0290_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__xor2_1 _0984_ (
    .A(_0260_),
    .B(_0261_),
    .X(_0292_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0985_ (
    .A(_0292_),
    .SLEEP(_0291_),
    .X(_0293_)
  );
  sky130_fd_sc_hd__clkinv_1 _0986_ (
    .A(_0293_),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__xor2_1 _0987_ (
    .A(_0262_),
    .B(_0263_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0988_ (
    .A(_0294_),
    .SLEEP(_0295_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__xnor2_1 _0989_ (
    .A(_0294_),
    .B(_0295_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__nand2_1 _0990_ (
    .A(\core.b_q [2]),
    .B(\core.a_q [3]),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__nand2_1 _0991_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [1]),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__nand2_1 _0992_ (
    .A(\core.b_q [3]),
    .B(\core.a_q [1]),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__xor2_1 _0993_ (
    .A(_0269_),
    .B(_0299_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__xnor2_1 _0994_ (
    .A(_0298_),
    .B(_0301_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__nand3_1 _0995_ (
    .A(\core.b_q [5]),
    .B(\core.a_q [0]),
    .C(_0302_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__xnor2_1 _0996_ (
    .A(_0271_),
    .B(_0273_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__nand2_1 _0997_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [4]),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__nand2_1 _0998_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [4]),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__and2_0 _0999_ (
    .A(_0278_),
    .B(_0305_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__o22ai_1 _1000_ (
    .A1(_0277_),
    .A2(_0306_),
    .B1(_0307_),
    .B2(_0054_),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__maj3_1 _1001_ (
    .A(_0269_),
    .B(_0298_),
    .C(_0299_),
    .X(_0309_)
  );
  sky130_fd_sc_hd__xnor3_1 _1002_ (
    .A(acc[6]),
    .B(_0276_),
    .C(_0277_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__xor2_1 _1003_ (
    .A(_0309_),
    .B(_0310_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__nand2_1 _1004_ (
    .A(_0308_),
    .B(_0311_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__xnor2_1 _1005_ (
    .A(_0308_),
    .B(_0311_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__maj3_1 _1006_ (
    .A(_0303_),
    .B(_0304_),
    .C(_0313_),
    .X(_0314_)
  );
  sky130_fd_sc_hd__xnor3_1 _1007_ (
    .A(_0274_),
    .B(_0275_),
    .C(_0285_),
    .X(_0315_)
  );
  sky130_fd_sc_hd__o21a_1 _1008_ (
    .A1(_0309_),
    .A2(_0310_),
    .B1(_0312_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__xnor2_1 _1009_ (
    .A(_0314_),
    .B(_0315_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__maj3_1 _1010_ (
    .A(_0314_),
    .B(_0315_),
    .C(_0316_),
    .X(_0318_)
  );
  sky130_fd_sc_hd__xnor2_1 _1011_ (
    .A(_0288_),
    .B(_0289_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1012_ (
    .A(_0319_),
    .SLEEP(_0318_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__xnor2_1 _1013_ (
    .A(_0291_),
    .B(_0292_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__and2_0 _1014_ (
    .A(_0320_),
    .B(_0321_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__nor2_1 _1015_ (
    .A(_0320_),
    .B(_0321_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__nand2_1 _1016_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [3]),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__nand2_1 _1017_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [3]),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__and2_0 _1018_ (
    .A(_0306_),
    .B(_0324_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__o22ai_1 _1019_ (
    .A1(_0305_),
    .A2(_0325_),
    .B1(_0326_),
    .B2(_0053_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__nand2_1 _1020_ (
    .A(\core.b_q [4]),
    .B(\core.a_q [0]),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__nand2_1 _1021_ (
    .A(\core.b_q [2]),
    .B(\core.a_q [2]),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__xor2_1 _1022_ (
    .A(_0300_),
    .B(_0328_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__maj3_1 _1023_ (
    .A(_0300_),
    .B(_0328_),
    .C(_0329_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__xnor3_1 _1024_ (
    .A(acc[5]),
    .B(_0278_),
    .C(_0305_),
    .X(_0332_)
  );
  sky130_fd_sc_hd__nor2_1 _1025_ (
    .A(_0331_),
    .B(_0332_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__xor2_1 _1026_ (
    .A(_0331_),
    .B(_0332_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__xnor2_1 _1027_ (
    .A(_0327_),
    .B(_0334_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__xnor2_1 _1028_ (
    .A(_0238_),
    .B(_0302_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__nand2b_1 _1029_ (
    .A_N(_0335_),
    .B(_0336_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__xnor3_1 _1030_ (
    .A(_0303_),
    .B(_0304_),
    .C(_0313_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__clkinv_1 _1031_ (
    .A(_0338_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__a21oi_1 _1032_ (
    .A1(_0327_),
    .A2(_0334_),
    .B1(_0333_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__maj3_1 _1033_ (
    .A(_0337_),
    .B(_0339_),
    .C(_0340_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__xnor2_1 _1034_ (
    .A(_0316_),
    .B(_0317_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__nor2_1 _1035_ (
    .A(_0341_),
    .B(_0342_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__xor2_1 _1036_ (
    .A(_0341_),
    .B(_0342_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__a21oi_1 _1037_ (
    .A1(acc[7]),
    .A2(_0344_),
    .B1(_0343_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__xnor2_1 _1038_ (
    .A(_0318_),
    .B(_0319_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1039_ (
    .A(_0346_),
    .SLEEP(_0345_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__nand2_1 _1040_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [2]),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__and2_0 _1041_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [2]),
    .X(_0349_)
  );
  sky130_fd_sc_hd__nand2_1 _1042_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [2]),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__and2_0 _1043_ (
    .A(_0325_),
    .B(_0348_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__o22ai_1 _1044_ (
    .A1(_0324_),
    .A2(_0350_),
    .B1(_0351_),
    .B2(_0052_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__nand2_1 _1045_ (
    .A(\core.b_q [2]),
    .B(\core.a_q [0]),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__nand4_1 _1046_ (
    .A(\core.b_q [3]),
    .B(\core.b_q [2]),
    .C(\core.a_q [1]),
    .D(\core.a_q [0]),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__xnor3_1 _1047_ (
    .A(acc[4]),
    .B(_0306_),
    .C(_0324_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__xor2_1 _1048_ (
    .A(_0354_),
    .B(_0355_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__nand2_1 _1049_ (
    .A(_0352_),
    .B(_0356_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1050_ (
    .A(_0352_),
    .SLEEP(_0356_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__xnor2_1 _1051_ (
    .A(_0329_),
    .B(_0330_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__nand3_1 _1052_ (
    .A(_0357_),
    .B(_0358_),
    .C(_0359_),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__xor2_1 _1053_ (
    .A(_0335_),
    .B(_0336_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__o21a_1 _1054_ (
    .A1(_0354_),
    .A2(_0355_),
    .B1(_0357_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__maj3_1 _1055_ (
    .A(_0360_),
    .B(_0361_),
    .C(_0362_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__xnor3_1 _1056_ (
    .A(_0337_),
    .B(_0338_),
    .C(_0340_),
    .X(_0364_)
  );
  sky130_fd_sc_hd__nor2_1 _1057_ (
    .A(_0363_),
    .B(_0364_),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__xor2_1 _1058_ (
    .A(acc[7]),
    .B(_0344_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__and2_0 _1059_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [1]),
    .X(_0367_)
  );
  sky130_fd_sc_hd__nand2_1 _1060_ (
    .A(\core.b_q [0]),
    .B(\core.a_q [1]),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__xnor2_1 _1061_ (
    .A(_0350_),
    .B(_0367_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__maj3_1 _1062_ (
    .A(acc[2]),
    .B(_0349_),
    .C(_0367_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__xnor3_1 _1063_ (
    .A(acc[3]),
    .B(_0325_),
    .C(_0348_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1064_ (
    .A(_0370_),
    .SLEEP(_0371_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__xnor2_1 _1065_ (
    .A(_0370_),
    .B(_0371_),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__a22oi_1 _1066_ (
    .A1(\core.b_q [2]),
    .A2(\core.a_q [1]),
    .B1(\core.a_q [0]),
    .B2(\core.b_q [3]),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1067_ (
    .A(_0354_),
    .SLEEP(_0374_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__a21oi_1 _1068_ (
    .A1(_0373_),
    .A2(_0375_),
    .B1(_0372_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__xnor3_1 _1069_ (
    .A(_0352_),
    .B(_0356_),
    .C(_0359_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__nor2_1 _1070_ (
    .A(_0376_),
    .B(_0377_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__xnor3_1 _1071_ (
    .A(_0360_),
    .B(_0361_),
    .C(_0362_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__xor2_1 _1072_ (
    .A(_0363_),
    .B(_0364_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__nand3_1 _1073_ (
    .A(_0378_),
    .B(_0379_),
    .C(_0380_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__nand2_1 _1074_ (
    .A(\core.b_q [1]),
    .B(\core.a_q [0]),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__xor2_1 _1075_ (
    .A(_0368_),
    .B(_0382_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__maj3_1 _1076_ (
    .A(_0051_),
    .B(_0368_),
    .C(_0382_),
    .X(_0384_)
  );
  sky130_fd_sc_hd__xnor2_1 _1077_ (
    .A(acc[2]),
    .B(_0369_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__xor2_1 _1078_ (
    .A(_0384_),
    .B(_0385_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__maj3_1 _1079_ (
    .A(_0353_),
    .B(_0384_),
    .C(_0385_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__xnor2_1 _1080_ (
    .A(_0373_),
    .B(_0375_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__nor2_1 _1081_ (
    .A(_0387_),
    .B(_0388_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__xor2_1 _1082_ (
    .A(_0376_),
    .B(_0377_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__nand3_1 _1083_ (
    .A(acc[0]),
    .B(\core.b_q [0]),
    .C(\core.a_q [0]),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__xnor2_1 _1084_ (
    .A(acc[1]),
    .B(_0383_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__nor2_1 _1085_ (
    .A(_0391_),
    .B(_0392_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__xnor2_1 _1086_ (
    .A(_0353_),
    .B(_0386_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__xor2_1 _1087_ (
    .A(_0387_),
    .B(_0388_),
    .X(_0395_)
  );
  sky130_fd_sc_hd__nand3_1 _1088_ (
    .A(_0393_),
    .B(_0394_),
    .C(_0395_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__xor2_1 _1089_ (
    .A(_0389_),
    .B(_0390_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__nor2b_1 _1090_ (
    .A(_0396_),
    .B_N(_0397_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__a21oi_1 _1091_ (
    .A1(_0389_),
    .A2(_0390_),
    .B1(_0378_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__xnor2_1 _1092_ (
    .A(_0379_),
    .B(_0399_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__a32oi_1 _1093_ (
    .A1(_0379_),
    .A2(_0389_),
    .A3(_0390_),
    .B1(_0398_),
    .B2(_0400_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__a21oi_1 _1094_ (
    .A1(_0378_),
    .A2(_0379_),
    .B1(_0380_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1095_ (
    .A(_0381_),
    .SLEEP(_0402_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__o21ai_0 _1096_ (
    .A1(_0401_),
    .A2(_0402_),
    .B1(_0381_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__xor2_1 _1097_ (
    .A(_0365_),
    .B(_0366_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__maj3_1 _1098_ (
    .A(_0365_),
    .B(_0366_),
    .C(_0404_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__xnor2_1 _1099_ (
    .A(_0345_),
    .B(_0346_),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__a21oi_1 _1100_ (
    .A1(_0406_),
    .A2(_0407_),
    .B1(_0347_),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__a211oi_1 _1101_ (
    .A1(_0406_),
    .A2(_0407_),
    .B1(_0322_),
    .C1(_0347_),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__nor2_1 _1102_ (
    .A(_0323_),
    .B(_0409_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__o31ai_1 _1103_ (
    .A1(_0297_),
    .A2(_0323_),
    .A3(_0409_),
    .B1(_0296_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__xnor2_1 _1104_ (
    .A(_0264_),
    .B(_0265_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__a21oi_1 _1105_ (
    .A1(_0411_),
    .A2(_0412_),
    .B1(_0266_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__xor2_1 _1106_ (
    .A(_0234_),
    .B(_0236_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__o21ai_0 _1107_ (
    .A1(_0413_),
    .A2(_0414_),
    .B1(_0237_),
    .Y(_0415_)
  );
  sky130_fd_sc_hd__xor2_1 _1108_ (
    .A(_0203_),
    .B(_0204_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__a21oi_1 _1109_ (
    .A1(_0415_),
    .A2(_0416_),
    .B1(_0205_),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__nor2_1 _1110_ (
    .A(_0148_),
    .B(_0174_),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1111_ (
    .A(_0175_),
    .SLEEP(_0418_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__o21ai_0 _1112_ (
    .A1(_0417_),
    .A2(_0418_),
    .B1(_0175_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__nor2_1 _1113_ (
    .A(_0166_),
    .B(_0169_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__maj3_1 _1114_ (
    .A(_0104_),
    .B(_0150_),
    .C(_0151_),
    .X(_0422_)
  );
  sky130_fd_sc_hd__a21oi_1 _1115_ (
    .A1(acc[14]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__xnor2_1 _1116_ (
    .A(acc[15]),
    .B(_0095_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__xor2_1 _1117_ (
    .A(_0104_),
    .B(_0424_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__xnor2_1 _1118_ (
    .A(_0423_),
    .B(_0425_),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__xnor2_1 _1119_ (
    .A(_0159_),
    .B(_0426_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__a21oi_1 _1120_ (
    .A1(_0162_),
    .A2(_0164_),
    .B1(_0427_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__nand3_1 _1121_ (
    .A(_0162_),
    .B(_0164_),
    .C(_0427_),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__nand2b_1 _1122_ (
    .A_N(_0428_),
    .B(_0429_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__nor2_1 _1123_ (
    .A(_0422_),
    .B(_0430_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__xnor2_1 _1124_ (
    .A(_0422_),
    .B(_0430_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__nor2_1 _1125_ (
    .A(_0421_),
    .B(_0432_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__xor2_1 _1126_ (
    .A(_0421_),
    .B(_0432_),
    .X(_0434_)
  );
  sky130_fd_sc_hd__and2_0 _1127_ (
    .A(_0171_),
    .B(_0434_),
    .X(_0435_)
  );
  sky130_fd_sc_hd__nor2_1 _1128_ (
    .A(_0171_),
    .B(_0434_),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__nor2_1 _1129_ (
    .A(_0435_),
    .B(_0436_),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__xnor2_1 _1130_ (
    .A(_0420_),
    .B(_0437_),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__nor2_1 _1131_ (
    .A(rst),
    .B(clear),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__o21ai_0 _1132_ (
    .A1(acc[15]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__a21oi_1 _1133_ (
    .A1(_0056_),
    .A2(_0438_),
    .B1(_0440_),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__xor2_1 _1134_ (
    .A(_0417_),
    .B(_0419_),
    .X(_0441_)
  );
  sky130_fd_sc_hd__o21ai_0 _1135_ (
    .A1(acc[14]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__a21oi_1 _1136_ (
    .A1(_0056_),
    .A2(_0441_),
    .B1(_0442_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__xnor2_1 _1137_ (
    .A(_0415_),
    .B(_0416_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__o21ai_0 _1138_ (
    .A1(acc[13]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__a21oi_1 _1139_ (
    .A1(_0056_),
    .A2(_0443_),
    .B1(_0444_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__xnor2_1 _1140_ (
    .A(_0413_),
    .B(_0414_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__o21ai_0 _1141_ (
    .A1(acc[12]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__a21oi_1 _1142_ (
    .A1(_0056_),
    .A2(_0445_),
    .B1(_0446_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__xnor2_1 _1143_ (
    .A(_0411_),
    .B(_0412_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__o21ai_0 _1144_ (
    .A1(acc[11]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0448_)
  );
  sky130_fd_sc_hd__a21oi_1 _1145_ (
    .A1(_0056_),
    .A2(_0447_),
    .B1(_0448_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__xnor2_1 _1146_ (
    .A(_0297_),
    .B(_0410_),
    .Y(_0449_)
  );
  sky130_fd_sc_hd__nor2_1 _1147_ (
    .A(acc[10]),
    .B(_0056_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__o21ai_0 _1148_ (
    .A1(_0057_),
    .A2(_0449_),
    .B1(_0439_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__nor2_1 _1149_ (
    .A(_0450_),
    .B(_0451_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1150_ (
    .A(_0322_),
    .SLEEP(_0323_),
    .X(_0452_)
  );
  sky130_fd_sc_hd__xnor2_1 _1151_ (
    .A(_0408_),
    .B(_0452_),
    .Y(_0453_)
  );
  sky130_fd_sc_hd__o21ai_0 _1152_ (
    .A1(acc[9]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__a21oi_1 _1153_ (
    .A1(_0056_),
    .A2(_0453_),
    .B1(_0454_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__xnor2_1 _1154_ (
    .A(_0406_),
    .B(_0407_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__o21ai_0 _1155_ (
    .A1(acc[8]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__a21oi_1 _1156_ (
    .A1(_0056_),
    .A2(_0455_),
    .B1(_0456_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__xnor2_1 _1157_ (
    .A(_0404_),
    .B(_0405_),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__o21ai_0 _1158_ (
    .A1(acc[7]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__a21oi_1 _1159_ (
    .A1(_0056_),
    .A2(_0457_),
    .B1(_0458_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__xor2_1 _1160_ (
    .A(_0401_),
    .B(_0403_),
    .X(_0459_)
  );
  sky130_fd_sc_hd__o21ai_0 _1161_ (
    .A1(acc[6]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__a21oi_1 _1162_ (
    .A1(_0056_),
    .A2(_0459_),
    .B1(_0460_),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__xnor2_1 _1163_ (
    .A(_0398_),
    .B(_0400_),
    .Y(_0461_)
  );
  sky130_fd_sc_hd__o21ai_0 _1164_ (
    .A1(acc[5]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__a21oi_1 _1165_ (
    .A1(_0056_),
    .A2(_0461_),
    .B1(_0462_),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__xor2_1 _1166_ (
    .A(_0396_),
    .B(_0397_),
    .X(_0463_)
  );
  sky130_fd_sc_hd__o21ai_0 _1167_ (
    .A1(acc[4]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__a21oi_1 _1168_ (
    .A1(_0056_),
    .A2(_0463_),
    .B1(_0464_),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__a21o_1 _1169_ (
    .A1(_0393_),
    .A2(_0394_),
    .B1(_0395_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__nand2_1 _1170_ (
    .A(_0396_),
    .B(_0465_),
    .Y(_0466_)
  );
  sky130_fd_sc_hd__o21ai_0 _1171_ (
    .A1(acc[3]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__a21oi_1 _1172_ (
    .A1(_0056_),
    .A2(_0466_),
    .B1(_0467_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__xnor2_1 _1173_ (
    .A(_0393_),
    .B(_0394_),
    .Y(_0468_)
  );
  sky130_fd_sc_hd__o21ai_0 _1174_ (
    .A1(acc[2]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__a21oi_1 _1175_ (
    .A1(_0056_),
    .A2(_0468_),
    .B1(_0469_),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__xnor2_1 _1176_ (
    .A(_0391_),
    .B(_0392_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__o21ai_0 _1177_ (
    .A1(acc[1]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__a21oi_1 _1178_ (
    .A1(_0056_),
    .A2(_0470_),
    .B1(_0471_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__a31oi_1 _1179_ (
    .A1(\core.b_q [0]),
    .A2(\core.a_q [0]),
    .A3(_0056_),
    .B1(acc[0]),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__o21ai_0 _1180_ (
    .A1(_0057_),
    .A2(_0391_),
    .B1(_0439_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__nor2_1 _1181_ (
    .A(_0472_),
    .B(_0473_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__nor4_1 _1182_ (
    .A(b[6]),
    .B(b[7]),
    .C(b[4]),
    .D(b[5]),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__nor2_1 _1183_ (
    .A(b[2]),
    .B(b[3]),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__nand2_1 _1184_ (
    .A(_0474_),
    .B(_0475_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__nor3_1 _1185_ (
    .A(b[0]),
    .B(b[1]),
    .C(_0476_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__nor4_1 _1186_ (
    .A(a[6]),
    .B(a[7]),
    .C(a[4]),
    .D(a[5]),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__nor4_1 _1187_ (
    .A(a[2]),
    .B(a[3]),
    .C(a[0]),
    .D(a[1]),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__a21oi_1 _1188_ (
    .A1(_0478_),
    .A2(_0479_),
    .B1(_0477_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__and2_0 _1189_ (
    .A(valid),
    .B(_0439_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__and3_1 _1190_ (
    .A(b[6]),
    .B(_0480_),
    .C(_0049_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__and3_1 _1191_ (
    .A(b[5]),
    .B(_0480_),
    .C(_0049_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__and3_1 _1192_ (
    .A(b[4]),
    .B(_0480_),
    .C(_0049_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__and3_1 _1193_ (
    .A(b[3]),
    .B(_0480_),
    .C(_0049_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__and3_1 _1194_ (
    .A(b[2]),
    .B(_0480_),
    .C(_0049_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__and3_1 _1195_ (
    .A(b[1]),
    .B(_0480_),
    .C(_0049_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__and3_1 _1196_ (
    .A(b[0]),
    .B(_0480_),
    .C(_0049_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__and3_1 _1197_ (
    .A(a[6]),
    .B(_0480_),
    .C(_0049_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__and3_1 _1198_ (
    .A(a[5]),
    .B(_0480_),
    .C(_0049_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__and3_1 _1199_ (
    .A(a[4]),
    .B(_0480_),
    .C(_0049_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__and3_1 _1200_ (
    .A(a[3]),
    .B(_0480_),
    .C(_0049_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__and3_1 _1201_ (
    .A(a[2]),
    .B(_0480_),
    .C(_0049_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__and3_1 _1202_ (
    .A(a[1]),
    .B(_0480_),
    .C(_0049_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__and3_1 _1203_ (
    .A(a[0]),
    .B(_0480_),
    .C(_0049_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__a21oi_1 _1204_ (
    .A1(acc[24]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0481_)
  );
  sky130_fd_sc_hd__xnor2_1 _1205_ (
    .A(acc[25]),
    .B(_0095_),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__xor2_1 _1206_ (
    .A(_0104_),
    .B(_0482_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__xnor2_1 _1207_ (
    .A(_0481_),
    .B(_0483_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__nor2_1 _1208_ (
    .A(_0156_),
    .B(_0484_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__a21oi_1 _1209_ (
    .A1(acc[23]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__xnor2_1 _1210_ (
    .A(acc[24]),
    .B(_0095_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__xor2_1 _1211_ (
    .A(_0104_),
    .B(_0487_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__xnor2_1 _1212_ (
    .A(_0486_),
    .B(_0488_),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__nand2_1 _1213_ (
    .A(_0485_),
    .B(_0489_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__maj3_1 _1214_ (
    .A(_0104_),
    .B(_0486_),
    .C(_0487_),
    .X(_0491_)
  );
  sky130_fd_sc_hd__nor2_1 _1215_ (
    .A(_0156_),
    .B(_0489_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__xnor2_1 _1216_ (
    .A(_0484_),
    .B(_0492_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__o21ai_0 _1217_ (
    .A1(_0491_),
    .A2(_0493_),
    .B1(_0490_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__maj3_1 _1218_ (
    .A(_0104_),
    .B(_0481_),
    .C(_0482_),
    .X(_0495_)
  );
  sky130_fd_sc_hd__a21oi_1 _1219_ (
    .A1(acc[25]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0496_)
  );
  sky130_fd_sc_hd__xnor2_1 _1220_ (
    .A(acc[26]),
    .B(_0095_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__xor2_1 _1221_ (
    .A(_0104_),
    .B(_0497_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__xnor2_1 _1222_ (
    .A(_0496_),
    .B(_0498_),
    .Y(_0499_)
  );
  sky130_fd_sc_hd__xnor2_1 _1223_ (
    .A(_0485_),
    .B(_0499_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__xnor2_1 _1224_ (
    .A(_0495_),
    .B(_0500_),
    .Y(_0501_)
  );
  sky130_fd_sc_hd__nand2b_1 _1225_ (
    .A_N(_0501_),
    .B(_0494_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__nor2_1 _1226_ (
    .A(_0156_),
    .B(_0499_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__nand2_1 _1227_ (
    .A(_0484_),
    .B(_0503_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__o21ai_0 _1228_ (
    .A1(_0495_),
    .A2(_0500_),
    .B1(_0504_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__maj3_1 _1229_ (
    .A(_0104_),
    .B(_0496_),
    .C(_0497_),
    .X(_0506_)
  );
  sky130_fd_sc_hd__a21oi_1 _1230_ (
    .A1(acc[26]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__xnor2_1 _1231_ (
    .A(acc[27]),
    .B(_0095_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__xor2_1 _1232_ (
    .A(_0104_),
    .B(_0508_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__xnor2_1 _1233_ (
    .A(_0507_),
    .B(_0509_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__xnor2_1 _1234_ (
    .A(_0503_),
    .B(_0510_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__xnor2_1 _1235_ (
    .A(_0506_),
    .B(_0511_),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__nand2b_1 _1236_ (
    .A_N(_0512_),
    .B(_0505_),
    .Y(_0513_)
  );
  sky130_fd_sc_hd__xor2_1 _1237_ (
    .A(_0505_),
    .B(_0512_),
    .X(_0514_)
  );
  sky130_fd_sc_hd__xnor2_1 _1238_ (
    .A(acc[23]),
    .B(_0095_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a21oi_1 _1239_ (
    .A1(acc[22]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__xor2_1 _1240_ (
    .A(_0104_),
    .B(_0515_),
    .X(_0517_)
  );
  sky130_fd_sc_hd__maj3_1 _1241_ (
    .A(_0104_),
    .B(_0515_),
    .C(_0516_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__xnor2_1 _1242_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__nor2_1 _1243_ (
    .A(_0156_),
    .B(_0519_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__xnor2_1 _1244_ (
    .A(_0489_),
    .B(_0520_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__nand2_1 _1245_ (
    .A(_0492_),
    .B(_0519_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__o21ai_0 _1246_ (
    .A1(_0518_),
    .A2(_0521_),
    .B1(_0522_),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__xnor2_1 _1247_ (
    .A(_0491_),
    .B(_0493_),
    .Y(_0524_)
  );
  sky130_fd_sc_hd__nand2b_1 _1248_ (
    .A_N(_0524_),
    .B(_0523_),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__xor2_1 _1249_ (
    .A(_0494_),
    .B(_0501_),
    .X(_0526_)
  );
  sky130_fd_sc_hd__xnor2_1 _1250_ (
    .A(acc[22]),
    .B(_0095_),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__a21oi_1 _1251_ (
    .A1(acc[21]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0528_)
  );
  sky130_fd_sc_hd__xor2_1 _1252_ (
    .A(_0104_),
    .B(_0527_),
    .X(_0529_)
  );
  sky130_fd_sc_hd__maj3_1 _1253_ (
    .A(_0104_),
    .B(_0527_),
    .C(_0528_),
    .X(_0530_)
  );
  sky130_fd_sc_hd__xnor2_1 _1254_ (
    .A(_0528_),
    .B(_0529_),
    .Y(_0531_)
  );
  sky130_fd_sc_hd__nor2_1 _1255_ (
    .A(_0156_),
    .B(_0531_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__xnor2_1 _1256_ (
    .A(_0519_),
    .B(_0532_),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__nand2_1 _1257_ (
    .A(_0520_),
    .B(_0531_),
    .Y(_0534_)
  );
  sky130_fd_sc_hd__o21ai_0 _1258_ (
    .A1(_0530_),
    .A2(_0533_),
    .B1(_0534_),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__xnor2_1 _1259_ (
    .A(_0518_),
    .B(_0521_),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__nand2b_1 _1260_ (
    .A_N(_0536_),
    .B(_0535_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__xor2_1 _1261_ (
    .A(_0523_),
    .B(_0524_),
    .X(_0538_)
  );
  sky130_fd_sc_hd__xnor2_1 _1262_ (
    .A(acc[21]),
    .B(_0095_),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__a21oi_1 _1263_ (
    .A1(acc[20]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0540_)
  );
  sky130_fd_sc_hd__xor2_1 _1264_ (
    .A(_0104_),
    .B(_0539_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__maj3_1 _1265_ (
    .A(_0104_),
    .B(_0539_),
    .C(_0540_),
    .X(_0542_)
  );
  sky130_fd_sc_hd__xnor2_1 _1266_ (
    .A(_0540_),
    .B(_0541_),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__nor2_1 _1267_ (
    .A(_0156_),
    .B(_0543_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__xnor2_1 _1268_ (
    .A(_0531_),
    .B(_0544_),
    .Y(_0545_)
  );
  sky130_fd_sc_hd__nand2_1 _1269_ (
    .A(_0532_),
    .B(_0543_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__o21ai_0 _1270_ (
    .A1(_0542_),
    .A2(_0545_),
    .B1(_0546_),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__xnor2_1 _1271_ (
    .A(_0530_),
    .B(_0533_),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__nand2b_1 _1272_ (
    .A_N(_0548_),
    .B(_0547_),
    .Y(_0549_)
  );
  sky130_fd_sc_hd__xor2_1 _1273_ (
    .A(_0535_),
    .B(_0536_),
    .X(_0550_)
  );
  sky130_fd_sc_hd__xnor2_1 _1274_ (
    .A(acc[20]),
    .B(_0095_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__a21oi_1 _1275_ (
    .A1(acc[19]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0552_)
  );
  sky130_fd_sc_hd__xor2_1 _1276_ (
    .A(_0104_),
    .B(_0551_),
    .X(_0553_)
  );
  sky130_fd_sc_hd__maj3_1 _1277_ (
    .A(_0104_),
    .B(_0551_),
    .C(_0552_),
    .X(_0554_)
  );
  sky130_fd_sc_hd__xnor2_1 _1278_ (
    .A(_0552_),
    .B(_0553_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__nor2_1 _1279_ (
    .A(_0156_),
    .B(_0555_),
    .Y(_0556_)
  );
  sky130_fd_sc_hd__xnor2_1 _1280_ (
    .A(_0543_),
    .B(_0556_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__nand2_1 _1281_ (
    .A(_0544_),
    .B(_0555_),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__o21ai_0 _1282_ (
    .A1(_0554_),
    .A2(_0557_),
    .B1(_0558_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__xnor2_1 _1283_ (
    .A(_0542_),
    .B(_0545_),
    .Y(_0560_)
  );
  sky130_fd_sc_hd__nand2b_1 _1284_ (
    .A_N(_0560_),
    .B(_0559_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__xor2_1 _1285_ (
    .A(_0547_),
    .B(_0548_),
    .X(_0562_)
  );
  sky130_fd_sc_hd__xnor2_1 _1286_ (
    .A(_0561_),
    .B(_0562_),
    .Y(_0563_)
  );
  sky130_fd_sc_hd__xnor2_1 _1287_ (
    .A(acc[19]),
    .B(_0095_),
    .Y(_0564_)
  );
  sky130_fd_sc_hd__a21oi_1 _1288_ (
    .A1(acc[18]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0565_)
  );
  sky130_fd_sc_hd__xor2_1 _1289_ (
    .A(_0104_),
    .B(_0564_),
    .X(_0566_)
  );
  sky130_fd_sc_hd__maj3_1 _1290_ (
    .A(_0104_),
    .B(_0564_),
    .C(_0565_),
    .X(_0567_)
  );
  sky130_fd_sc_hd__xnor2_1 _1291_ (
    .A(_0565_),
    .B(_0566_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__nor2_1 _1292_ (
    .A(_0156_),
    .B(_0568_),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__xnor2_1 _1293_ (
    .A(_0555_),
    .B(_0569_),
    .Y(_0570_)
  );
  sky130_fd_sc_hd__nand2_1 _1294_ (
    .A(_0556_),
    .B(_0568_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__o21ai_0 _1295_ (
    .A1(_0567_),
    .A2(_0570_),
    .B1(_0571_),
    .Y(_0572_)
  );
  sky130_fd_sc_hd__xnor2_1 _1296_ (
    .A(_0554_),
    .B(_0557_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__nand2b_1 _1297_ (
    .A_N(_0573_),
    .B(_0572_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__xor2_1 _1298_ (
    .A(_0559_),
    .B(_0560_),
    .X(_0575_)
  );
  sky130_fd_sc_hd__xnor2_1 _1299_ (
    .A(acc[18]),
    .B(_0095_),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__a21oi_1 _1300_ (
    .A1(acc[17]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0577_)
  );
  sky130_fd_sc_hd__xor2_1 _1301_ (
    .A(_0104_),
    .B(_0576_),
    .X(_0578_)
  );
  sky130_fd_sc_hd__maj3_1 _1302_ (
    .A(_0104_),
    .B(_0576_),
    .C(_0577_),
    .X(_0579_)
  );
  sky130_fd_sc_hd__xnor2_1 _1303_ (
    .A(_0577_),
    .B(_0578_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__nor2_1 _1304_ (
    .A(_0156_),
    .B(_0580_),
    .Y(_0581_)
  );
  sky130_fd_sc_hd__xnor2_1 _1305_ (
    .A(_0568_),
    .B(_0581_),
    .Y(_0582_)
  );
  sky130_fd_sc_hd__nand2_1 _1306_ (
    .A(_0569_),
    .B(_0580_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__o21ai_0 _1307_ (
    .A1(_0579_),
    .A2(_0582_),
    .B1(_0583_),
    .Y(_0584_)
  );
  sky130_fd_sc_hd__xnor2_1 _1308_ (
    .A(_0567_),
    .B(_0570_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__nand2b_1 _1309_ (
    .A_N(_0585_),
    .B(_0584_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__xor2_1 _1310_ (
    .A(_0572_),
    .B(_0573_),
    .X(_0587_)
  );
  sky130_fd_sc_hd__xnor2_1 _1311_ (
    .A(acc[17]),
    .B(_0095_),
    .Y(_0588_)
  );
  sky130_fd_sc_hd__a21oi_1 _1312_ (
    .A1(acc[16]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0589_)
  );
  sky130_fd_sc_hd__xor2_1 _1313_ (
    .A(_0104_),
    .B(_0588_),
    .X(_0590_)
  );
  sky130_fd_sc_hd__maj3_1 _1314_ (
    .A(_0104_),
    .B(_0588_),
    .C(_0589_),
    .X(_0591_)
  );
  sky130_fd_sc_hd__xnor2_1 _1315_ (
    .A(_0589_),
    .B(_0590_),
    .Y(_0592_)
  );
  sky130_fd_sc_hd__nor2_1 _1316_ (
    .A(_0156_),
    .B(_0592_),
    .Y(_0593_)
  );
  sky130_fd_sc_hd__xnor2_1 _1317_ (
    .A(_0580_),
    .B(_0593_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__nor2_1 _1318_ (
    .A(_0591_),
    .B(_0594_),
    .Y(_0595_)
  );
  sky130_fd_sc_hd__a21oi_1 _1319_ (
    .A1(_0581_),
    .A2(_0592_),
    .B1(_0595_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__xnor2_1 _1320_ (
    .A(_0579_),
    .B(_0582_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1321_ (
    .A(_0596_),
    .SLEEP(_0597_),
    .X(_0598_)
  );
  sky130_fd_sc_hd__xor2_1 _1322_ (
    .A(_0584_),
    .B(_0585_),
    .X(_0599_)
  );
  sky130_fd_sc_hd__maj3_1 _1323_ (
    .A(_0104_),
    .B(_0423_),
    .C(_0424_),
    .X(_0600_)
  );
  sky130_fd_sc_hd__a21oi_1 _1324_ (
    .A1(_0157_),
    .A2(_0426_),
    .B1(_0158_),
    .Y(_0601_)
  );
  sky130_fd_sc_hd__a21oi_1 _1325_ (
    .A1(acc[15]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0602_)
  );
  sky130_fd_sc_hd__xnor2_1 _1326_ (
    .A(acc[16]),
    .B(_0095_),
    .Y(_0603_)
  );
  sky130_fd_sc_hd__xor2_1 _1327_ (
    .A(_0104_),
    .B(_0603_),
    .X(_0604_)
  );
  sky130_fd_sc_hd__xnor2_1 _1328_ (
    .A(_0602_),
    .B(_0604_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__nor2_1 _1329_ (
    .A(_0156_),
    .B(_0605_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__xnor2_1 _1330_ (
    .A(_0157_),
    .B(_0605_),
    .Y(_0607_)
  );
  sky130_fd_sc_hd__xor2_1 _1331_ (
    .A(_0601_),
    .B(_0607_),
    .X(_0608_)
  );
  sky130_fd_sc_hd__xnor2_1 _1332_ (
    .A(_0600_),
    .B(_0608_),
    .Y(_0609_)
  );
  sky130_fd_sc_hd__o21a_1 _1333_ (
    .A1(_0428_),
    .A2(_0431_),
    .B1(_0609_),
    .X(_0610_)
  );
  sky130_fd_sc_hd__maj3_1 _1334_ (
    .A(_0600_),
    .B(_0601_),
    .C(_0607_),
    .X(_0611_)
  );
  sky130_fd_sc_hd__maj3_1 _1335_ (
    .A(_0104_),
    .B(_0602_),
    .C(_0603_),
    .X(_0612_)
  );
  sky130_fd_sc_hd__xnor2_1 _1336_ (
    .A(_0592_),
    .B(_0606_),
    .Y(_0613_)
  );
  sky130_fd_sc_hd__xnor2_1 _1337_ (
    .A(_0612_),
    .B(_0613_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__nor2_1 _1338_ (
    .A(_0611_),
    .B(_0614_),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__xor2_1 _1339_ (
    .A(_0611_),
    .B(_0614_),
    .X(_0616_)
  );
  sky130_fd_sc_hd__nor3_1 _1340_ (
    .A(_0428_),
    .B(_0431_),
    .C(_0609_),
    .Y(_0617_)
  );
  sky130_fd_sc_hd__nor2_1 _1341_ (
    .A(_0610_),
    .B(_0617_),
    .Y(_0618_)
  );
  sky130_fd_sc_hd__nand2_1 _1342_ (
    .A(_0433_),
    .B(_0618_),
    .Y(_0619_)
  );
  sky130_fd_sc_hd__a21oi_1 _1343_ (
    .A1(_0420_),
    .A2(_0437_),
    .B1(_0435_),
    .Y(_0620_)
  );
  sky130_fd_sc_hd__xnor2_1 _1344_ (
    .A(_0433_),
    .B(_0618_),
    .Y(_0621_)
  );
  sky130_fd_sc_hd__o21ai_0 _1345_ (
    .A1(_0620_),
    .A2(_0621_),
    .B1(_0619_),
    .Y(_0622_)
  );
  sky130_fd_sc_hd__xor2_1 _1346_ (
    .A(_0610_),
    .B(_0616_),
    .X(_0623_)
  );
  sky130_fd_sc_hd__maj3_1 _1347_ (
    .A(_0610_),
    .B(_0616_),
    .C(_0622_),
    .X(_0624_)
  );
  sky130_fd_sc_hd__nand2_1 _1348_ (
    .A(_0593_),
    .B(_0605_),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__o21ai_0 _1349_ (
    .A1(_0612_),
    .A2(_0613_),
    .B1(_0625_),
    .Y(_0626_)
  );
  sky130_fd_sc_hd__xnor2_1 _1350_ (
    .A(_0591_),
    .B(_0594_),
    .Y(_0627_)
  );
  sky130_fd_sc_hd__nand2b_1 _1351_ (
    .A_N(_0627_),
    .B(_0626_),
    .Y(_0628_)
  );
  sky130_fd_sc_hd__xnor2_1 _1352_ (
    .A(_0626_),
    .B(_0627_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__nand2_1 _1353_ (
    .A(_0615_),
    .B(_0629_),
    .Y(_0630_)
  );
  sky130_fd_sc_hd__xor2_1 _1354_ (
    .A(_0615_),
    .B(_0629_),
    .X(_0631_)
  );
  sky130_fd_sc_hd__nand2_1 _1355_ (
    .A(_0624_),
    .B(_0631_),
    .Y(_0632_)
  );
  sky130_fd_sc_hd__nand2_1 _1356_ (
    .A(_0596_),
    .B(_0597_),
    .Y(_0633_)
  );
  sky130_fd_sc_hd__nand2_1 _1357_ (
    .A(_0598_),
    .B(_0633_),
    .Y(_0634_)
  );
  sky130_fd_sc_hd__xor2_1 _1358_ (
    .A(_0628_),
    .B(_0634_),
    .X(_0635_)
  );
  sky130_fd_sc_hd__a21oi_1 _1359_ (
    .A1(_0628_),
    .A2(_0630_),
    .B1(_0634_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__a31oi_1 _1360_ (
    .A1(_0624_),
    .A2(_0631_),
    .A3(_0635_),
    .B1(_0636_),
    .Y(_0637_)
  );
  sky130_fd_sc_hd__xnor2_1 _1361_ (
    .A(_0598_),
    .B(_0599_),
    .Y(_0638_)
  );
  sky130_fd_sc_hd__maj3_1 _1362_ (
    .A(_0598_),
    .B(_0599_),
    .C(_0637_),
    .X(_0639_)
  );
  sky130_fd_sc_hd__xnor2_1 _1363_ (
    .A(_0586_),
    .B(_0587_),
    .Y(_0640_)
  );
  sky130_fd_sc_hd__maj3_1 _1364_ (
    .A(_0586_),
    .B(_0587_),
    .C(_0639_),
    .X(_0641_)
  );
  sky130_fd_sc_hd__xnor2_1 _1365_ (
    .A(_0574_),
    .B(_0575_),
    .Y(_0642_)
  );
  sky130_fd_sc_hd__maj3_1 _1366_ (
    .A(_0574_),
    .B(_0575_),
    .C(_0641_),
    .X(_0643_)
  );
  sky130_fd_sc_hd__maj3_1 _1367_ (
    .A(_0561_),
    .B(_0562_),
    .C(_0643_),
    .X(_0644_)
  );
  sky130_fd_sc_hd__xnor2_1 _1368_ (
    .A(_0549_),
    .B(_0550_),
    .Y(_0645_)
  );
  sky130_fd_sc_hd__maj3_1 _1369_ (
    .A(_0549_),
    .B(_0550_),
    .C(_0644_),
    .X(_0646_)
  );
  sky130_fd_sc_hd__xnor2_1 _1370_ (
    .A(_0537_),
    .B(_0538_),
    .Y(_0647_)
  );
  sky130_fd_sc_hd__maj3_1 _1371_ (
    .A(_0537_),
    .B(_0538_),
    .C(_0646_),
    .X(_0648_)
  );
  sky130_fd_sc_hd__xnor2_1 _1372_ (
    .A(_0525_),
    .B(_0526_),
    .Y(_0649_)
  );
  sky130_fd_sc_hd__maj3_1 _1373_ (
    .A(_0525_),
    .B(_0526_),
    .C(_0648_),
    .X(_0650_)
  );
  sky130_fd_sc_hd__xnor2_1 _1374_ (
    .A(_0502_),
    .B(_0514_),
    .Y(_0651_)
  );
  sky130_fd_sc_hd__maj3_1 _1375_ (
    .A(_0502_),
    .B(_0514_),
    .C(_0650_),
    .X(_0652_)
  );
  sky130_fd_sc_hd__nor2_1 _1376_ (
    .A(_0156_),
    .B(_0510_),
    .Y(_0653_)
  );
  sky130_fd_sc_hd__nand2_1 _1377_ (
    .A(_0499_),
    .B(_0653_),
    .Y(_0654_)
  );
  sky130_fd_sc_hd__o21ai_0 _1378_ (
    .A1(_0506_),
    .A2(_0511_),
    .B1(_0654_),
    .Y(_0655_)
  );
  sky130_fd_sc_hd__maj3_1 _1379_ (
    .A(_0104_),
    .B(_0507_),
    .C(_0508_),
    .X(_0656_)
  );
  sky130_fd_sc_hd__a21oi_1 _1380_ (
    .A1(acc[27]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0657_)
  );
  sky130_fd_sc_hd__xnor2_1 _1381_ (
    .A(acc[28]),
    .B(_0095_),
    .Y(_0658_)
  );
  sky130_fd_sc_hd__xor2_1 _1382_ (
    .A(_0104_),
    .B(_0658_),
    .X(_0659_)
  );
  sky130_fd_sc_hd__xnor2_1 _1383_ (
    .A(_0657_),
    .B(_0659_),
    .Y(_0660_)
  );
  sky130_fd_sc_hd__xnor2_1 _1384_ (
    .A(_0653_),
    .B(_0660_),
    .Y(_0661_)
  );
  sky130_fd_sc_hd__nor2_1 _1385_ (
    .A(_0656_),
    .B(_0661_),
    .Y(_0662_)
  );
  sky130_fd_sc_hd__xnor2_1 _1386_ (
    .A(_0656_),
    .B(_0661_),
    .Y(_0663_)
  );
  sky130_fd_sc_hd__nand2b_1 _1387_ (
    .A_N(_0663_),
    .B(_0655_),
    .Y(_0664_)
  );
  sky130_fd_sc_hd__xor2_1 _1388_ (
    .A(_0655_),
    .B(_0663_),
    .X(_0665_)
  );
  sky130_fd_sc_hd__nor2_1 _1389_ (
    .A(_0513_),
    .B(_0665_),
    .Y(_0666_)
  );
  sky130_fd_sc_hd__xnor2_1 _1390_ (
    .A(_0513_),
    .B(_0665_),
    .Y(_0667_)
  );
  sky130_fd_sc_hd__nor2_1 _1391_ (
    .A(_0652_),
    .B(_0667_),
    .Y(_0668_)
  );
  sky130_fd_sc_hd__nor2_1 _1392_ (
    .A(_0156_),
    .B(_0660_),
    .Y(_0669_)
  );
  sky130_fd_sc_hd__a21oi_1 _1393_ (
    .A1(_0510_),
    .A2(_0669_),
    .B1(_0662_),
    .Y(_0670_)
  );
  sky130_fd_sc_hd__maj3_1 _1394_ (
    .A(_0104_),
    .B(_0657_),
    .C(_0658_),
    .X(_0671_)
  );
  sky130_fd_sc_hd__a21oi_1 _1395_ (
    .A1(acc[28]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0672_)
  );
  sky130_fd_sc_hd__xnor2_1 _1396_ (
    .A(acc[29]),
    .B(_0095_),
    .Y(_0673_)
  );
  sky130_fd_sc_hd__xor2_1 _1397_ (
    .A(_0104_),
    .B(_0673_),
    .X(_0674_)
  );
  sky130_fd_sc_hd__xnor2_1 _1398_ (
    .A(_0672_),
    .B(_0674_),
    .Y(_0675_)
  );
  sky130_fd_sc_hd__xnor2_1 _1399_ (
    .A(_0669_),
    .B(_0675_),
    .Y(_0676_)
  );
  sky130_fd_sc_hd__nor2_1 _1400_ (
    .A(_0671_),
    .B(_0676_),
    .Y(_0677_)
  );
  sky130_fd_sc_hd__xnor2_1 _1401_ (
    .A(_0671_),
    .B(_0676_),
    .Y(_0678_)
  );
  sky130_fd_sc_hd__nor2_1 _1402_ (
    .A(_0670_),
    .B(_0678_),
    .Y(_0679_)
  );
  sky130_fd_sc_hd__xnor2_1 _1403_ (
    .A(_0670_),
    .B(_0678_),
    .Y(_0680_)
  );
  sky130_fd_sc_hd__xnor2_1 _1404_ (
    .A(_0664_),
    .B(_0680_),
    .Y(_0681_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1405_ (
    .A(_0664_),
    .SLEEP(_0666_),
    .X(_0682_)
  );
  sky130_fd_sc_hd__o32ai_1 _1406_ (
    .A1(_0652_),
    .A2(_0667_),
    .A3(_0681_),
    .B1(_0682_),
    .B2(_0680_),
    .Y(_0683_)
  );
  sky130_fd_sc_hd__nor2_1 _1407_ (
    .A(_0156_),
    .B(_0675_),
    .Y(_0684_)
  );
  sky130_fd_sc_hd__and2_0 _1408_ (
    .A(_0660_),
    .B(_0684_),
    .X(_0685_)
  );
  sky130_fd_sc_hd__maj3_1 _1409_ (
    .A(_0104_),
    .B(_0672_),
    .C(_0673_),
    .X(_0686_)
  );
  sky130_fd_sc_hd__a21o_1 _1410_ (
    .A1(acc[29]),
    .A2(_0095_),
    .B1(_0093_),
    .X(_0687_)
  );
  sky130_fd_sc_hd__xnor2_1 _1411_ (
    .A(acc[30]),
    .B(_0095_),
    .Y(_0688_)
  );
  sky130_fd_sc_hd__xnor2_1 _1412_ (
    .A(_0104_),
    .B(_0688_),
    .Y(_0689_)
  );
  sky130_fd_sc_hd__xnor2_1 _1413_ (
    .A(_0687_),
    .B(_0689_),
    .Y(_0690_)
  );
  sky130_fd_sc_hd__nor3_1 _1414_ (
    .A(_0156_),
    .B(_0675_),
    .C(_0690_),
    .Y(_0691_)
  );
  sky130_fd_sc_hd__xor2_1 _1415_ (
    .A(_0684_),
    .B(_0690_),
    .X(_0692_)
  );
  sky130_fd_sc_hd__xnor2_1 _1416_ (
    .A(_0686_),
    .B(_0692_),
    .Y(_0693_)
  );
  sky130_fd_sc_hd__o21ai_0 _1417_ (
    .A1(_0677_),
    .A2(_0685_),
    .B1(_0693_),
    .Y(_0694_)
  );
  sky130_fd_sc_hd__nor3_1 _1418_ (
    .A(_0677_),
    .B(_0685_),
    .C(_0693_),
    .Y(_0695_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1419_ (
    .A(_0694_),
    .SLEEP(_0695_),
    .X(_0696_)
  );
  sky130_fd_sc_hd__xor2_1 _1420_ (
    .A(_0679_),
    .B(_0696_),
    .X(_0697_)
  );
  sky130_fd_sc_hd__xnor2_1 _1421_ (
    .A(_0683_),
    .B(_0697_),
    .Y(_0698_)
  );
  sky130_fd_sc_hd__o21ai_0 _1422_ (
    .A1(acc[30]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0699_)
  );
  sky130_fd_sc_hd__a21oi_1 _1423_ (
    .A1(_0056_),
    .A2(_0698_),
    .B1(_0699_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__nor2_1 _1424_ (
    .A(_0666_),
    .B(_0668_),
    .Y(_0700_)
  );
  sky130_fd_sc_hd__xnor2_1 _1425_ (
    .A(_0681_),
    .B(_0700_),
    .Y(_0701_)
  );
  sky130_fd_sc_hd__o21ai_0 _1426_ (
    .A1(acc[29]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0702_)
  );
  sky130_fd_sc_hd__a21oi_1 _1427_ (
    .A1(_0056_),
    .A2(_0701_),
    .B1(_0702_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__xnor2_1 _1428_ (
    .A(_0652_),
    .B(_0667_),
    .Y(_0703_)
  );
  sky130_fd_sc_hd__o21ai_0 _1429_ (
    .A1(acc[28]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0704_)
  );
  sky130_fd_sc_hd__a21oi_1 _1430_ (
    .A1(_0056_),
    .A2(_0703_),
    .B1(_0704_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1431_ (
    .A(_0049_),
    .SLEEP(_0480_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__xnor2_1 _1432_ (
    .A(_0650_),
    .B(_0651_),
    .Y(_0705_)
  );
  sky130_fd_sc_hd__o21ai_0 _1433_ (
    .A1(acc[27]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0706_)
  );
  sky130_fd_sc_hd__a21oi_1 _1434_ (
    .A1(_0056_),
    .A2(_0705_),
    .B1(_0706_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__xnor2_1 _1435_ (
    .A(_0648_),
    .B(_0649_),
    .Y(_0707_)
  );
  sky130_fd_sc_hd__o21ai_0 _1436_ (
    .A1(acc[26]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0708_)
  );
  sky130_fd_sc_hd__a21oi_1 _1437_ (
    .A1(_0056_),
    .A2(_0707_),
    .B1(_0708_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__xnor2_1 _1438_ (
    .A(_0646_),
    .B(_0647_),
    .Y(_0709_)
  );
  sky130_fd_sc_hd__o21ai_0 _1439_ (
    .A1(acc[25]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0710_)
  );
  sky130_fd_sc_hd__a21oi_1 _1440_ (
    .A1(_0056_),
    .A2(_0709_),
    .B1(_0710_),
    .Y(_0036_)
  );
  sky130_fd_sc_hd__xnor2_1 _1441_ (
    .A(_0644_),
    .B(_0645_),
    .Y(_0711_)
  );
  sky130_fd_sc_hd__o21ai_0 _1442_ (
    .A1(acc[24]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0712_)
  );
  sky130_fd_sc_hd__a21oi_1 _1443_ (
    .A1(_0056_),
    .A2(_0711_),
    .B1(_0712_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__xnor2_1 _1444_ (
    .A(_0563_),
    .B(_0643_),
    .Y(_0713_)
  );
  sky130_fd_sc_hd__o21ai_0 _1445_ (
    .A1(acc[23]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0714_)
  );
  sky130_fd_sc_hd__a21oi_1 _1446_ (
    .A1(_0056_),
    .A2(_0713_),
    .B1(_0714_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__xnor2_1 _1447_ (
    .A(_0641_),
    .B(_0642_),
    .Y(_0715_)
  );
  sky130_fd_sc_hd__o21ai_0 _1448_ (
    .A1(acc[22]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0716_)
  );
  sky130_fd_sc_hd__a21oi_1 _1449_ (
    .A1(_0056_),
    .A2(_0715_),
    .B1(_0716_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__xnor2_1 _1450_ (
    .A(_0639_),
    .B(_0640_),
    .Y(_0717_)
  );
  sky130_fd_sc_hd__o21ai_0 _1451_ (
    .A1(acc[21]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0718_)
  );
  sky130_fd_sc_hd__a21oi_1 _1452_ (
    .A1(_0056_),
    .A2(_0717_),
    .B1(_0718_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__xnor2_1 _1453_ (
    .A(_0637_),
    .B(_0638_),
    .Y(_0719_)
  );
  sky130_fd_sc_hd__o21ai_0 _1454_ (
    .A1(acc[20]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0720_)
  );
  sky130_fd_sc_hd__a21oi_1 _1455_ (
    .A1(_0056_),
    .A2(_0719_),
    .B1(_0720_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__nand2_1 _1456_ (
    .A(_0630_),
    .B(_0632_),
    .Y(_0721_)
  );
  sky130_fd_sc_hd__xnor2_1 _1457_ (
    .A(_0635_),
    .B(_0721_),
    .Y(_0722_)
  );
  sky130_fd_sc_hd__o21ai_0 _1458_ (
    .A1(acc[19]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0723_)
  );
  sky130_fd_sc_hd__a21oi_1 _1459_ (
    .A1(_0056_),
    .A2(_0722_),
    .B1(_0723_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__xnor2_1 _1460_ (
    .A(_0624_),
    .B(_0631_),
    .Y(_0724_)
  );
  sky130_fd_sc_hd__o21ai_0 _1461_ (
    .A1(acc[18]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0725_)
  );
  sky130_fd_sc_hd__a21oi_1 _1462_ (
    .A1(_0056_),
    .A2(_0724_),
    .B1(_0725_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__xnor2_1 _1463_ (
    .A(_0622_),
    .B(_0623_),
    .Y(_0726_)
  );
  sky130_fd_sc_hd__o21ai_0 _1464_ (
    .A1(acc[17]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0727_)
  );
  sky130_fd_sc_hd__a21oi_1 _1465_ (
    .A1(_0056_),
    .A2(_0726_),
    .B1(_0727_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__maj3_1 _1466_ (
    .A(_0679_),
    .B(_0683_),
    .C(_0696_),
    .X(_0728_)
  );
  sky130_fd_sc_hd__mux2i_1 _1467_ (
    .A0(_0104_),
    .A1(_0688_),
    .S(_0687_),
    .Y(_0729_)
  );
  sky130_fd_sc_hd__o21ai_0 _1468_ (
    .A1(_0104_),
    .A2(_0688_),
    .B1(_0729_),
    .Y(_0730_)
  );
  sky130_fd_sc_hd__a21oi_1 _1469_ (
    .A1(acc[30]),
    .A2(_0095_),
    .B1(_0093_),
    .Y(_0731_)
  );
  sky130_fd_sc_hd__xor2_1 _1470_ (
    .A(acc[31]),
    .B(_0095_),
    .X(_0732_)
  );
  sky130_fd_sc_hd__xnor2_1 _1471_ (
    .A(_0731_),
    .B(_0732_),
    .Y(_0733_)
  );
  sky130_fd_sc_hd__xnor2_1 _1472_ (
    .A(_0730_),
    .B(_0733_),
    .Y(_0734_)
  );
  sky130_fd_sc_hd__nor3b_1 _1473_ (
    .A(_0684_),
    .B(_0686_),
    .C_N(_0690_),
    .Y(_0735_)
  );
  sky130_fd_sc_hd__a21oi_1 _1474_ (
    .A1(_0686_),
    .A2(_0691_),
    .B1(_0735_),
    .Y(_0736_)
  );
  sky130_fd_sc_hd__xnor2_1 _1475_ (
    .A(_0734_),
    .B(_0736_),
    .Y(_0737_)
  );
  sky130_fd_sc_hd__xnor2_1 _1476_ (
    .A(_0694_),
    .B(_0737_),
    .Y(_0738_)
  );
  sky130_fd_sc_hd__xnor2_1 _1477_ (
    .A(_0728_),
    .B(_0738_),
    .Y(_0739_)
  );
  sky130_fd_sc_hd__o21ai_0 _1478_ (
    .A1(acc[31]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0740_)
  );
  sky130_fd_sc_hd__a21oi_1 _1479_ (
    .A1(_0056_),
    .A2(_0739_),
    .B1(_0740_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__and2_0 _1480_ (
    .A(\core.valid_q ),
    .B(_0439_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__and3_1 _1481_ (
    .A(a[7]),
    .B(_0480_),
    .C(_0049_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__and3_1 _1482_ (
    .A(b[7]),
    .B(_0480_),
    .C(_0049_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__xnor2_1 _1483_ (
    .A(_0620_),
    .B(_0621_),
    .Y(_0741_)
  );
  sky130_fd_sc_hd__o21ai_0 _1484_ (
    .A1(acc[16]),
    .A2(_0056_),
    .B1(_0439_),
    .Y(_0742_)
  );
  sky130_fd_sc_hd__a21oi_1 _1485_ (
    .A1(_0056_),
    .A2(_0741_),
    .B1(_0742_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__dfxtp_1 _1486_ (
    .CLK(clk),
    .D(_0033_),
    .Q(\core.zero_q )
  );
  sky130_fd_sc_hd__dfxtp_1 _1487_ (
    .CLK(clk),
    .D(_0015_),
    .Q(acc[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1488_ (
    .CLK(clk),
    .D(_0014_),
    .Q(acc[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _1489_ (
    .CLK(clk),
    .D(_0013_),
    .Q(acc[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _1490_ (
    .CLK(clk),
    .D(_0012_),
    .Q(acc[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _1491_ (
    .CLK(clk),
    .D(_0011_),
    .Q(acc[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _1492_ (
    .CLK(clk),
    .D(_0010_),
    .Q(acc[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _1493_ (
    .CLK(clk),
    .D(_0009_),
    .Q(acc[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _1494_ (
    .CLK(clk),
    .D(_0008_),
    .Q(acc[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _1495_ (
    .CLK(clk),
    .D(_0007_),
    .Q(acc[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _1496_ (
    .CLK(clk),
    .D(_0006_),
    .Q(acc[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _1497_ (
    .CLK(clk),
    .D(_0005_),
    .Q(acc[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _1498_ (
    .CLK(clk),
    .D(_0004_),
    .Q(acc[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _1499_ (
    .CLK(clk),
    .D(_0003_),
    .Q(acc[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _1500_ (
    .CLK(clk),
    .D(_0002_),
    .Q(acc[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _1501_ (
    .CLK(clk),
    .D(_0001_),
    .Q(acc[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _1502_ (
    .CLK(clk),
    .D(_0000_),
    .Q(acc[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _1503_ (
    .CLK(clk),
    .D(_0050_),
    .Q(acc[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _1504_ (
    .CLK(clk),
    .D(_0044_),
    .Q(acc[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _1505_ (
    .CLK(clk),
    .D(_0043_),
    .Q(acc[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _1506_ (
    .CLK(clk),
    .D(_0042_),
    .Q(acc[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _1507_ (
    .CLK(clk),
    .D(_0041_),
    .Q(acc[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _1508_ (
    .CLK(clk),
    .D(_0040_),
    .Q(acc[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _1509_ (
    .CLK(clk),
    .D(_0039_),
    .Q(acc[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _1510_ (
    .CLK(clk),
    .D(_0038_),
    .Q(acc[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _1511_ (
    .CLK(clk),
    .D(_0037_),
    .Q(acc[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _1512_ (
    .CLK(clk),
    .D(_0036_),
    .Q(acc[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _1513_ (
    .CLK(clk),
    .D(_0035_),
    .Q(acc[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _1514_ (
    .CLK(clk),
    .D(_0034_),
    .Q(acc[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _1515_ (
    .CLK(clk),
    .D(_0032_),
    .Q(acc[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _1516_ (
    .CLK(clk),
    .D(_0031_),
    .Q(acc[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _1517_ (
    .CLK(clk),
    .D(_0030_),
    .Q(acc[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _1518_ (
    .CLK(clk),
    .D(_0045_),
    .Q(acc[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _1519_ (
    .CLK(clk),
    .D(_0046_),
    .Q(out_valid)
  );
  sky130_fd_sc_hd__dfxtp_1 _1520_ (
    .CLK(clk),
    .D(_0029_),
    .Q(\core.a_q [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1521_ (
    .CLK(clk),
    .D(_0028_),
    .Q(\core.a_q [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _1522_ (
    .CLK(clk),
    .D(_0027_),
    .Q(\core.a_q [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _1523_ (
    .CLK(clk),
    .D(_0026_),
    .Q(\core.a_q [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _1524_ (
    .CLK(clk),
    .D(_0025_),
    .Q(\core.a_q [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _1525_ (
    .CLK(clk),
    .D(_0024_),
    .Q(\core.a_q [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _1526_ (
    .CLK(clk),
    .D(_0023_),
    .Q(\core.a_q [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _1527_ (
    .CLK(clk),
    .D(_0047_),
    .Q(\core.a_q [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _1528_ (
    .CLK(clk),
    .D(_0022_),
    .Q(\core.b_q [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1529_ (
    .CLK(clk),
    .D(_0021_),
    .Q(\core.b_q [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _1530_ (
    .CLK(clk),
    .D(_0020_),
    .Q(\core.b_q [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _1531_ (
    .CLK(clk),
    .D(_0019_),
    .Q(\core.b_q [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _1532_ (
    .CLK(clk),
    .D(_0018_),
    .Q(\core.b_q [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _1533_ (
    .CLK(clk),
    .D(_0017_),
    .Q(\core.b_q [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _1534_ (
    .CLK(clk),
    .D(_0016_),
    .Q(\core.b_q [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _1535_ (
    .CLK(clk),
    .D(_0048_),
    .Q(\core.b_q [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _1536_ (
    .CLK(clk),
    .D(_0049_),
    .Q(\core.valid_q )
  );
endmodule
