#!/bin/bash
# Recompute G1 power from the RETAINED acts_*.tcl files -- no re-simulation.
#
# Why this exists: run_g1.sh deleted each window VCD after its power report
# succeeded, so re-deriving toggle counts would cost ~25 min of gate-level sim
# per point. But the acts files survived, and they *are* the input to
# report_power: set_power_activity -pins {...} -activity <toggles/ns>.
# Two things are wrong with those numbers (docs/S3.2 "绝对功耗刻度更正"):
#   1. the divisor was the window's END time (12000 ns) instead of its
#      DURATION (5000 ns)                       -> x2.4
#   2. the tb clock is 10 ns/cycle (100 MHz) while the SDC says 20 ns (50 MHz),
#      so the profiled rate is 2x the operating point  -> x0.5
# Net scale for the constrained operating point: 2.4 * 0.5 = 1.2.
# We therefore multiply every injected activity by SCALE and re-report, this
# time with -digits 9 because power_*.txt only carried 3 significant digits and
# that rounding is what made the auto-vs-B3 gaps (0.5%) unresolvable.
#
# Residual limit, state it when quoting results: the toggle counts themselves
# were generated by a sim driven at 100 MHz, so glitch yield is not identical to
# a genuine 50 MHz run. Scaling fixes bookkeeping, not glitch physics. A clean
# number still needs run_g1.sh (now fixed) re-run at TB_HALF_NS=10.
#
# Usage: g1_recompute_from_acts.sh [config ...]     (default: one validation point)
#   e.g. g1_recompute_from_acts.sh p60T4_b0 p60T4_b3 p60T4_auto
set -u
B3=/mnt/e/科研/B3_CHIP_IHP
FLOW=$HOME/orfs-git/flow
# Platform-parameterised: defaults are the sky130hd G1 grid; point WORK/SCALE at the
# IHP run to re-report those points instead (SCALE=1 there -- that pipeline already
# uses the corrected window and an SDC-matched clock).
PLAT=${PLAT:-sky130hd}
NICK=${NICK:-b3_chip}
BASE=${BASE:-$FLOW/results/$PLAT/$NICK/base}
# Liberty filename differs per platform, so it cannot be derived from $PLAT alone.
DEF_LIB=$FLOW/platforms/$PLAT/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
[ "$PLAT" = "ihp-sg13g2" ] && DEF_LIB=$FLOW/platforms/$PLAT/lib/sg13g2_stdcell_typ_1p20V_25C.lib
LIB=${LIB:-$DEF_LIB}
RULES=${RULES:-$FLOW/platforms/$PLAT/rcx_patterns.rules}
SDC=${SDC:-$BASE/6_1_fill.sdc}
WORK=${WORK:-$HOME/b3_ihp/g1}
ARCH=${ARCH:-"/mnt/e/科研/WSL工作区/g1"}
B3ACTB=$B3/scripts/build_activity_tcl.py
SCALE=${SCALE:-1.2}
STAGE=${STAGE:-run}
DEFAULT_CFGS="p60T4_b3"
CFGS=("$@"); [ ${#CFGS[@]} -eq 0 ] && CFGS=($DEFAULT_CFGS)

if [ "$STAGE" = "sdf" ]; then
  # build_activity files reference *pin* activities only, so no SDF is needed to
  # re-report; this stage exists to refresh the SDF used by future sims.
  echo "nothing to do here; run_g1.sh sdf owns that"
  exit 0
fi

for name in "${CFGS[@]}"; do
  ACT=$WORK/acts_$name.tcl
  [ -s "$ACT" ] || { echo "SKIP $name: no $ACT"; continue; }
  SCALED=$WORK/acts_${name}_x$(echo $SCALE | tr . p).tcl
  python3 - "$ACT" "$SCALED" "$SCALE" <<'PY'
import re, sys
src, dst, k = sys.argv[1], sys.argv[2], float(sys.argv[3])
pat = re.compile(r"(-activity\s+)([0-9.eE+-]+)")
n = [0]
def rep(m):
    n[0] += 1
    return "%s%.9g" % (m.group(1), float(m.group(2)) * k)
out = pat.sub(rep, open(src, encoding="utf-8", errors="replace").read())
out = out.replace("# window ", "# window(was) ")
open(dst, "w", encoding="utf-8").write(
    "# rescaled x%g per g1_recompute_from_acts.sh (window divisor x2.4, 100->50MHz x0.5)\n" % k
    + out)
print("  %s: scaled %d activity values x%g -> %s" % (src.split('/')[-1], n[0], k, dst.split('/')[-1]))
PY
  cat > $WORK/re_$name.tcl <<EOF
read_liberty $LIB
read_db $BASE/6_final.odb
read_sdc $SDC
set_propagated_clock [all_clocks]
define_process_corner -ext_model_index 0 X
extract_parasitics -ext_model_file $RULES
source $SCALED
report_power -digits 9 > $WORK/repower_$name.txt
EOF
  ( cd $FLOW && openroad -exit $WORK/re_$name.tcl ) > $WORK/re_$name.log 2>&1
  rc=$?
  echo "REPOW $name rc=$rc"
  grep -E '^(Total|Sequential|Combinational|Clock|Group|-----)' $WORK/repower_$name.txt 2>/dev/null | head -8
  old=$(grep -h '^Total' $WORK/power_$name.txt 2>/dev/null | awk '{print $5}')
  new=$(grep -h '^Total' $WORK/repower_$name.txt 2>/dev/null | awk '{print $5}')
  [ -n "$old" ] && [ -n "$new" ] && python3 -c "
import sys
o, n, k = float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3])
print('  TOTAL recorded %.6g -> rescaled %.6g  (x%.4f; naive expectation x%.4f)'
      % (o, n, n / o, k))
print('  the total moves far less than the injected-activity scale because')
print('  report_power derives the Clock group (and FF clock pins) from the SDC')
print('  period, not from set_power_activity -pins -- see docs/S3.2.')
" "$old" "$new" "$SCALE"
  cp -f $WORK/repower_$name.txt $ARCH/ 2>/dev/null
done
echo "RECOMPUTE_DONE $(date '+%F %T')"
